### DISCUSSION TITLE
Can't get URL for camera

### DISCUSSION THREAD

**Discussion by slingshot74** [fuatakgun/eufy_security#1047] [Q&A]
Hi,

First of all. Thank you so much for this pluign. I really would like to get my eufy camera in HA.

I have followed the installation steps and installed the WebCRT through the link.

I use the code to show the camera as in the description

```
type: custom:webrtc-camera
entity: camera.voordeur
poster: image.entrance_event_image
ui: true
shortcuts:
  - name: Play
    icon: mdi:play
    service: camera.turn_on
    service_data:
      entity_id: camera.voordeur
  - name: Stop
    icon: mdi:stop
    service: camera.turn_off
    service_data:
      entity_id: camera.voordeur
``` 

I get the error. Can't get URL for camera.voordeur (my camera is called voordeur).
![image](https://github.com/fuatakgun/eufy_security/assets/125136823/f6d45c3f-c084-4f26-b618-7a030d05e6d7)

![image](https://github.com/fuatakgun/eufy_security/assets/125136823/aca2344c-7b59-4fa3-9a18-41f33ef097fc)

![image](https://github.com/fuatakgun/eufy_security/assets/125136823/2e33f82c-7439-45d3-b12a-9809790cf3fb)

It has a streaming URL:
![image](https://github.com/fuatakgun/eufy_security/assets/125136823/a6d8adf2-fa16-41cc-a107-d9d9b93e1948)
