### DISCUSSION TITLE
small indentation issue in automation exemple inside README.md

### DISCUSSION THREAD

**Discussion by mdrolo** [fuatakgun/eufy_security#1083] [General]
Hi,

first, a huge thanks for the work done around this. It's a great job and allow me to integrate my eufy cams.

I'm a beginer so, excuse me if i'm wrong. I may found a identation error in the [automation exemple](https://github.com/fuatakgun/eufy_security?tab=readme-ov-file#send-notification-with-thumbnail-from-home-assistant) . My Home Assistant complain about that part.

in the documentation : 
```yaml
        sequence:
          - delay:
            hours: 0
            minutes: 0
            seconds: 3
            milliseconds: 0
          - service: notify.mobile_app_fuatx3pro
```

after correction : 

```yaml
        sequence:
          - delay:
              hours: 0
              minutes: 0
              seconds: 3
              milliseconds: 0
          - service: notify.mobile_app_fuatx3pro
```

I also note that, in addition to the the camera name, there is also the notify.mobile_app_fuatx3pro to adapt to my configuration.
