### DISCUSSION TITLE
Eufy Smart Lock T8502 entities

### DISCUSSION THREAD

**Discussion by ben-simpson-4realz** [fuatakgun/eufy_security#1117] [Q&A]
Hello, first of all thank you for creating this project. I think this is awesome! 

I'm trying to get unlock/lock capability for my Eufy T8502 Smart Lock in home assistant. I've installed the custom integration and am using the manual docker install of eufy-security-ws. 

It seems like the device is recognized in home assistant now. (Finds the correct mac address and model number). But the associated entities it creates seem like ones you'd find with an alarm rather than a smart lock. Here's some screenshots from the integration. Thanks for any help!
![Screenshot_20240306_121933_Home Assistant](https://github.com/fuatakgun/eufy_security/assets/12087786/5e5b6fc3-6b7d-4851-b3c4-bf6d53a4835e)
![Screenshot_20240306_121948_Home Assistant](https://github.com/fuatakgun/eufy_security/assets/12087786/f4e7e44a-a44f-4bb1-badd-9ac4d715c19f)

**Comment by Mark-Bohle** [comment]
Did you ever find a solution to this?  I have similar problems
![image](https://github.com/user-attachments/assets/eb2c3300-f6ef-49a3-bd5f-213174a0aff5)

**Reply by ben-simpson-4realz** [reply]
Hi, yes I was able to get it working. I think there may have been a couple reasons it didn't work at first. Here's what I did.

In my setup, I'm using the docker install of eufy-security-ws. I think support was added for this lock after I first tried it, so I did a docker pull to get the latest updates to the docker image. 

Also, I think initially I tried to map a custom port, which didn't work for me. I ended up needing to use "network_mode: host" for it to work. Here's my compose file that ended up working for me. (Just need to add your own username, password & path to your eufy-security-ws docker volume).

```
eufy-security-ws:
    container_name: eufy-lock
    network_mode: host
    restart: unless-stopped
    environment:
      - USERNAME=<usernameFromEufyAppHere>
      - PASSWORD=<passwordFromEufyAppHere>
      - PORT=3000
    volumes:
      - </path/to/docker/here>/data:/data
    image: bropat/eufy-security-ws:latest
```

After this, I saw the lock entities under diagnostics in Home Assistant (they were disabled/greyed out at first). After I enabled them everything worked!

![Screenshot_20250224_002741_Home Assistant](https://github.com/user-attachments/assets/88e156b3-b9b3-4791-8397-97de92f2ddb8)

Hope this helps!
