### DISCUSSION TITLE
Where are the physical thumbnails stored?

### DISCUSSION THREAD

**Discussion by starman2k01** [fuatakgun/eufy_security#1140] [Q&A]
I want to send the thumbnail to my Nvidia Shield, but I have to have the path for the thumbnail. All I can find is outside url, which doesn't work--it says "website:8123/api/image_proxy/image.gate_event_image?token=xxxxxxxxxxx. I need the actual .jpg path. There is no "api/image_proxy" path on my RPi???

**Comment by Clem-** [comment]
You can use the service `camera.snapshot` to store the last event image whenever you want.

Example:
```
service: camera.snapshot
target:
  entity_id: camera.my_cam
data:
  filename: /your_path/{{entity_id}}.jpg
```
