### DISCUSSION TITLE
How to configure webrtc card for P2P-only device?

### DISCUSSION THREAD

**Discussion by slymas** [fuatakgun/eufy_security#1358] [Q&A]
Hey all,

I have recently set up this integration for my cameras, using the default WebRTC config. I have multiple Eufycam2 devices (T8114-Z and T8114), and 1 Doorbell S330 (T8213). I enabled RTSP stream for all the Eufycam2s in the configuration but it seems like the doorbell only supports P2P. Then, I added the following cards for all my cameras:

```
type: custom:webrtc-camera
entity: camera.doorbell
poster: image.doorbell_event_image
ui: true
shortcuts:
  - name: Play
    icon: mdi:play
    service: camera.turn_on
    service_data:
      entity_id: camera.doorbell
  - name: Stop
    icon: mdi:stop
    service: camera.turn_off
    service_data:
      entity_id: camera.doorbell
```

The Eufycam2s are streaming fine, even without lowering the video settings, the stream gets running almost quicker than in the Eufy app. However, the Doorbell has issues starting the streams: it gives a grey image first and then the image appears if I move between tabs or reload the dash without stopping the stream. I get a nice image from the doorbell if I first start the stream via the "start p2p stream" diagnostic entity and then open the dash. 

And now comes my problem: if I try using the `start_rtsp_livestream`, or `start_p2p_livestream` services on my webrtc card it fails with "unknown service" or similar. I checked the code of this repo briefly and it seems like the livestream services are in https://github.com/fuatakgun/eufy_security/blob/master/custom_components/eufy_security/services.yaml, but the `turn_on` isn't. So I am probably pulling the services from the wrong file (I am still just starting out with HA and don't know much about dashboards and cards).

My questions are:
 - Should `turn_on` work as expected with a P2P-only device?
 - How can I modify my card to start the stream for the doorbell right away?
