### DISCUSSION TITLE
Thumbnail Update Automation

### DISCUSSION THREAD

**Discussion by shanelord01** [fuatakgun/eufy_security#789] [General]
Not sure if I'm recreating the wheel here but after getting my dashboard setup, I wanted the thumbnails to update regularly throughout the day and night. Perhaps this might help others.

Side note - couldn't get the streams working without adding `stream:` to my HA configuration.yaml

**Note**: Battery check is to ensure the camera responds, otherwise the automation times out. Delays are because the system seems to choke if you ask cameras to start and stop too quickly.

```
alias: Update Eufy Thumbnail Hourly
description: ""
trigger:
  - platform: time_pattern
    hours: /1
condition: []
action:
  - if:
      - condition: numeric_state
        entity_id: sensor.driveway_camera_1_battery_percentage
        above: 20
    then:
      - service: camera.turn_on
        data: {}
        target:
          entity_id: camera.driveway_camera_1
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: camera.turn_off
        data: {}
        target:
          entity_id: camera.driveway_camera_1
    else:
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - if:
      - condition: numeric_state
        entity_id: sensor.driveway_camera_2
        above: 20
    then:
      - service: camera.turn_on
        data: {}
        target:
          entity_id: camera.driveway_camera_2
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: camera.turn_off
        data: {}
        target:
          entity_id: camera.driveway_camera_2
    else:
      - stop: ""
mode: single
```

**Comment by bkr1969** [comment]
How outdated is this?  I get an unknow homeassistant error when calling ```camera.turn_on```.

**Reply by shanelord01** [reply]
I've changed the original above to the below - apologies I'd forgotten I'd posted this or I would have updated it :)

```
alias: Camera - Eufy Image Update
description: v2 of the script using RTSP on off
trigger:
  - platform: time_pattern
    hours: /1
condition: []
action:
  - if:
      - condition: numeric_state
        entity_id: sensor.driveway_camera_2_battery_percentage
        above: 20
    then:
      - service: eufy_security.start_rtsp_livestream
        metadata: {}
        data: {}
        target:
          entity_id: camera.driveway_camera_2
      - service: eufy_security.generate_image
        metadata: {}
        data: {}
        enabled: false
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - service: eufy_security.stop_rtsp_livestream
        metadata: {}
        data: {}
        target:
          entity_id: camera.driveway_camera_2
    else:
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - if:
      - condition: numeric_state
        entity_id: sensor.powerwall_battery_percentage
        above: 20
    then:
      - service: eufy_security.start_rtsp_livestream
        metadata: {}
        data: {}
        target:
          entity_id: camera.powerwall
      - service: eufy_security.generate_image
        metadata: {}
        data: {}
        enabled: false
      - delay:
          hours: 0
          minutes: 10
          seconds: 0
          milliseconds: 0
      - service: eufy_security.stop_rtsp_livestream
        metadata: {}
        data: {}
        target:
          entity_id: camera.powerwall
    else:
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - if:
      - condition: numeric_state
        entity_id: sensor.side_gate_battery_percentage
        above: 20
    then:
      - service: eufy_security.start_rtsp_livestream
        metadata: {}
        data: {}
        target:
          entity_id: camera.side_gate
      - service: eufy_security.generate_image
        metadata: {}
        data: {}
        enabled: false
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - service: eufy_security.stop_rtsp_livestream
        metadata: {}
        data: {}
        target:
          entity_id: camera.side_gate
    else:
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - if:
      - condition: numeric_state
        entity_id: sensor.swimming_pool_battery_percentage
        above: 20
    then:
      - service: eufy_security.start_rtsp_livestream
        metadata: {}
        data: {}
        target:
          entity_id: camera.swimming_pool
      - service: eufy_security.generate_image
        metadata: {}
        data: {}
        enabled: false
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - service: eufy_security.stop_rtsp_livestream
        metadata: {}
        data: {}
        target:
          entity_id: camera.swimming_pool
    else:
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - if:
      - condition: numeric_state
        entity_id: sensor.dog_pen_1_battery_percentage
        above: 20
    then:
      - service: eufy_security.start_rtsp_livestream
        metadata: {}
        data: {}
        target:
          entity_id: camera.dog_pen_1
      - service: eufy_security.generate_image
        metadata: {}
        data: {}
        enabled: false
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - service: eufy_security.stop_rtsp_livestream
        metadata: {}
        data: {}
        target:
          entity_id: camera.dog_pen_1
    else:
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - if:
      - condition: numeric_state
        entity_id: sensor.dog_pen_2_battery_percentage
        above: 20
    then:
      - service: eufy_security.start_rtsp_livestream
        metadata: {}
        data: {}
        target:
          entity_id: camera.dog_pen_2
      - service: eufy_security.generate_image
        metadata: {}
        data: {}
        enabled: false
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - service: eufy_security.stop_rtsp_livestream
        metadata: {}
        data: {}
        target:
          entity_id: camera.dog_pen_2
    else: []
mode: single
```
I then made a dashboard with this code. Note there are some other cameras here too that aren't Eufy.

```
square: false
type: grid
cards:
  - show_state: true
    show_name: true
    camera_view: auto
    type: picture-entity
    entity: camera.g4_doorbell_pro_high
  - show_state: true
    show_name: true
    camera_view: auto
    type: picture-entity
    entity: camera.g4_doorbell_pro_package_camera
  - show_state: true
    show_name: true
    camera_view: auto
    type: picture-entity
    entity: camera.g4_pro_high
  - square: false
    columns: 1
    type: grid
    cards:
      - type: conditional
        conditions:
          - entity: camera.driveway_camera_2
            state: idle
        card:
          show_state: true
          show_name: true
          type: picture-entity
          entity: camera.driveway_camera_2
          camera_image: camera.driveway_camera_2
          tap_action:
            action: call-service
            service: camera.turn_on
            data: {}
            target:
              entity_id: camera.driveway_camera_2
      - type: conditional
        conditions:
          - entity: camera.driveway_camera_2
            state: streaming
        card:
          type: vertical-stack
          cards:
            - show_name: true
              show_icon: false
              type: button
              tap_action:
                action: call-service
                service: camera.turn_off
                data: {}
                target:
                  entity_id: camera.driveway_camera_2
              entity: camera.driveway_camera_2
              name: Stop
            - type: custom:webrtc-camera
              entity: camera.driveway_camera_2
  - show_state: true
    show_name: true
    camera_view: auto
    type: picture-entity
    entity: camera.g3_instant_high
  - type: picture-entity
    entity: camera.g4_instant_high_2
  - type: picture-entity
    entity: camera.g4_instant_high
  - square: false
    columns: 1
    type: grid
    cards:
      - type: conditional
        conditions:
          - entity: camera.dog_pen_1
            state: idle
        card:
          show_state: true
          show_name: true
          type: picture-entity
          entity: camera.dog_pen_1
          camera_image: camera.dog_pen_1
          tap_action:
            action: call-service
            service: camera.turn_on
            data: {}
            target:
              entity_id: camera.dog_pen_1
      - type: conditional
        conditions:
          - entity: camera.dog_pen_1
            state: streaming
        card:
          type: vertical-stack
          cards:
            - show_name: true
              show_icon: false
              type: button
              tap_action:
                action: call-service
                service: camera.turn_off
                data: {}
                target:
                  entity_id: camera.dog_pen_1
              entity: camera.dog_pen_1
              name: Stop
            - type: custom:webrtc-camera
              entity: camera.dog_pen_1
  - square: false
    columns: 1
    type: grid
    cards:
      - type: conditional
        conditions:
          - entity: camera.dog_pen_2
            state: idle
        card:
          show_state: true
          show_name: true
          type: picture-entity
          entity: camera.dog_pen_2
          camera_image: camera.dog_pen_2
          tap_action:
            action: call-service
            service: camera.turn_on
            data: {}
            target:
              entity_id: camera.dog_pen_2
      - type: conditional
        conditions:
          - entity: camera.dog_pen_2
            state: streaming
        card:
          type: vertical-stack
          cards:
            - show_name: true
              show_icon: false
              type: button
              tap_action:
                action: call-service
                service: camera.turn_off
                data: {}
                target:
                  entity_id: camera.dog_pen_2
              entity: camera.dog_pen_2
              name: Stop
            - type: custom:webrtc-camera
              entity: camera.dog_pen_2
  - square: false
    columns: 1
    type: grid
    cards:
      - type: conditional
        conditions:
          - entity: camera.powerwall
            state: idle
        card:
          show_state: true
          show_name: true
          type: picture-entity
          entity: camera.powerwall
          camera_image: camera.powerwall
          tap_action:
            action: call-service
            service: camera.turn_on
            data: {}
            target:
              entity_id: camera.powerwall
      - type: conditional
        conditions:
          - entity: camera.powerwall
            state: streaming
        card:
          type: vertical-stack
          cards:
            - show_name: true
              show_icon: false
              type: button
              tap_action:
                action: call-service
                service: camera.turn_off
                data: {}
                target:
                  entity_id: camera.powerwall
              entity: camera.powerwall
              name: Stop
            - type: custom:webrtc-camera
              entity: camera.powerwall
  - square: false
    columns: 1
    type: grid
    cards:
      - type: conditional
        conditions:
          - entity: camera.side_gate
            state: idle
        card:
          show_state: true
          show_name: true
          type: picture-entity
          entity: camera.side_gate
          camera_image: camera.driveway_camera_2
          tap_action:
            action: call-service
            service: camera.turn_on
            data: {}
            target:
              entity_id: camera.side_gate
      - type: conditional
        conditions:
          - entity: camera.side_gate
            state: streaming
        card:
          type: vertical-stack
          cards:
            - show_name: true
              show_icon: false
              type: button
              tap_action:
                action: call-service
                service: camera.turn_off
                data: {}
                target:
                  entity_id: camera.side_gate
              entity: camera.side_gate
              name: Stop
            - type: custom:webrtc-camera
              entity: camera.side_gate
  - square: false
    columns: 1
    type: grid
    cards:
      - type: conditional
        conditions:
          - entity: camera.swimming_pool
            state: idle
        card:
          show_state: true
          show_name: true
          type: picture-entity
          entity: camera.swimming_pool
          camera_image: camera.swimming_pool
          tap_action:
            action: call-service
            service: camera.turn_on
            data: {}
            target:
              entity_id: camera.swimming_pool
      - type: conditional
        conditions:
          - entity: camera.swimming_pool
            state: streaming
        card:
          type: vertical-stack
          cards:
            - show_name: true
              show_icon: false
              type: button
              tap_action:
                action: call-service
                service: camera.turn_off
                data: {}
                target:
                  entity_id: camera.swimming_pool
              entity: camera.swimming_pool
              name: Stop
            - type: custom:webrtc-camera
              entity: camera.swimming_pool
```
