### DISCUSSION TITLE
Long delay difference between Eufy App motion detection and [eufy_security.generate_image + camera.snapshot] photo capture

### DISCUSSION THREAD

**Discussion by sesardelaisla** [fuatakgun/eufy_security#865] [Q&A]
Hello Everyone,

I am an Eufy new user. I just purchased a kit with one HomeBase 2 (T8010) and 4x eufyCam 2 Pro (T8140). Before registering a new issue, I would love to get some feedback from the community or developers to check whether the behaviour I am experiencing with my current addon+integration setup is due to some real problem or it is just a misconfiguration. I am posting here because I think the specific automation tasks are performed by the integration. Please, do advise should I share this in a different place. Thanks!

Basically, I have done a Home Assistant automation to get a photo capture upon motion detection, for sending it to a Telegram group. The purpose is to add in such group to nearby family or neighbours when necessary, so they can get some photos in case I am flying somewhere (no cellphone coverage). With this, they could call the police being 100% sure that the alarm is not false. Photos are being captured and reaching Telegram just in a few seconds.

The first keyframe that is displayed in the Eufy app recorded clip makes sense. The clip starts just when a person enters the camera frame. However, **the image extracted from the RTSP stream** with the eufy_security.generate_image + camera.snapshot services **is delayed about 12 seconds later the app's first keyframe**:

![eufy_delay_comparison](https://github.com/fuatakgun/eufy_security/assets/81921573/9e8189fe-71a4-4971-81d8-31d8e5646ffc)

Please, do find the automation I am testing this with below:

```
alias: "Eufy: Telegram de imágenes 2CPro 04"
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.eufy_2cpro_04_person_detected
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.eufy_2cpro_04_motion_detected
    to: "on"
condition: []
action:
  - service: eufy_security.start_rtsp_livestream
    data: {}
    target:
      entity_id: camera.eufy_2cpro_04
  - service: eufy_security.generate_image
    data: {}
    target:
      entity_id: camera.eufy_2cpro_04
  - service: camera.snapshot
    data:
      filename: www/snapshots/eufy_2cpro_04_latest_01.jpg
    target:
      entity_id: camera.eufy_2cpro_04
  - service: camera.snapshot
    data:
      filename: www/snapshots/eufy_2cpro_04_latest_02.jpg
    target:
      entity_id: camera.eufy_2cpro_04
  - service: camera.snapshot
    data:
      filename: www/snapshots/eufy_2cpro_04_latest_03.jpg
    target:
      entity_id: camera.eufy_2cpro_04
  - service: notify.cesar_telegram
    data:
      message: Movimiento sospechoso
      data:
        photo:
          - file: www/snapshots/eufy_2cpro_04_latest_01.jpg
            caption: Foto 2CPro04 1/3
  - service: notify.cesar_telegram
    data:
      message: Movimiento sospechoso
      data:
        photo:
          - file: www/snapshots/eufy_2cpro_04_latest_02.jpg
            caption: Foto 2CPro04 2/3
  - service: notify.cesar_telegram
    data:
      message: Movimiento sospechoso
      data:
        photo:
          - file: www/snapshots/eufy_2cpro_04_latest_03.jpg
            caption: Foto 2CPro04 3/3
  - service: eufy_security.stop_rtsp_livestream
    data: {}
    target:
      entity_id: camera.eufy_2cpro_04
  - service: notify.mobile_app_sesars_iphone
    data:
      message: Motion detected
      data:
        image: /api/camera_proxy/camera.eufy_2cpro_04
    enabled: false
mode: single

```

The image file `www/snapshots/eufy_2cpro_04_latest_01.jpg` created after the `camera.snapshot` step is the one that you can see above in the image as "Automation". The other two captures (eufy_2cpro_04_latest_02.jpg and eufy_2cpro_04_latest_03.jpg) have of course an even later timestamp (about +2" after the previous one) . Obviously, this makes this workflow useless, because the person is already out of frame. Is this something that can be fixed? Is the automation workflow wrong? Should I redo the automation in a different way of there is no way to get the actual first frame?

NOTE: I just tried to remove the `eufy_security.generate_image` step from the automation and **delay has been reduced from 12" to 7"** **(???)**. Although this is much better, such delay is still not useful for the purpose.

In case it is not possible to get an earlier frame for this workflow to be useful, is there anyway (or is it planned) to get the clip stored in the local HUB, which by the way I believe that it would be the most efficient way to do this for the purpose?

Thanks in advanced.

Sésar
