### DISCUSSION TITLE
How to attach camera image into an email message

### DISCUSSION THREAD

**Discussion by AseKarlsson** [fuatakgun/eufy_security#932] [Q&A]
Hi,

I have an image entity (image.doorbell_event_image) that shows up nice in HA.
How can I attach that into an email notification?

This works fine:
```
  - service: notify.email_user
    data:
      title: Doorbell
      message: Doorbell
```

But if I add what I think would be correct, I don’t even receive an email:
```
  - service: notify.email_user
    data:
      title: Doorbell
      message: Doorbell
      image: /api/image_proxy/image.doorbell_event_image
```

Ideas anyone?

Thanks
