### DISCUSSION TITLE
Eufy Security Web socket: “Missing one of USERNAME or PASSWORD”

### DISCUSSION THREAD

**Discussion by cldparisi** [fuatakgun/eufy_security#983] [Q&A]
I installed Eufy Security Web socket on Dockers but when the docker starts it always gives an error “Missing one of USERNAME or PASSWORD” user and pwd are entered and are correct but the block comes from the Eufy API because they recognize the access as an “attack”, in fact I received it to warn me of a suspicious attempt

I only put in the Yaml:

```
eufy-security-ws:
    image: bropat/eufy-security-ws
    container_name: eufy-security-ws
    ports:
      - "3000:3000"
    environment:
      - EUFY_EMAIL=YourEmailAddress
      - EUFY_PASSWORD=YourPassword
      - EUFY_PERSISTENT_LOGIN=false
    restart: always
```

anything else?

**Comment by cldparisi** [comment]
I solved it, I'll post it in case anyone needs it.
All the environment variables that I had previously found were wrong, I found the correct ones:
https://github.com/fuatakgun/eufy_security/discussions/612

```
  eufy-security-ws:
    # https://github.com/fuatakgun/eufy_security/discussions/612
    image: bropat/eufy-security-ws
    container_name: eufy-security-ws
    network_mode: "bridge"
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Amsterdam
      - USERNAME=myUser
      - PASSWORD=myPwd
      - COUNTRY=IT
    restart: unless-stopped

```
