### ISSUE TITLE
Error: Can't get URL for Camera

### ISSUE THREAD

**Issue by protomota** [fuatakgun/eufy_security#1044]
This was a previous bug report but was closed with a request to open with proper documentation. Issue still remains.

https://github.com/fuatakgun/eufy_security/issues/287

Error shows up at the top of Dashboard cards when trying to add a camera by entity ID. It seems to mostly be an issue with battery cameras, but I also see it intermittently with my plugin Eufy Indoor Cam E220 pan and tilt camera. I believe this is an issue related to the fact that battery cameras do not have a constant RTSP stream and rather only start the stream when motion is detected on the camera. I believe the error may be coming from either go2rtc or WebRTC, so it may need to be raised in one of those projects. But it also may be an integration issue, so I was hoping it could be looked into here first. 

I have found that if you add the camera with the direct URL in the Dashboard card, the camera streams work fine, but this solution does not allow for previous event images to be displayed as poster images when the RTSP stream is not available.

**To reproduce**

1. Add a Dashboard card with the boilerplate yaml from the documentation and update the camera entity name with a battery operated camera that supports RTSP.
2. Notice the error at the top of the card.

**Expected behavior**

Stream would display for camera after camera detects motion without an error, and a poster image would be displayed from the previous event when the stream stops.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): VM Home Assistant OS
- Home Assistant Core Version: core-2023.12.3
- Eufy Security Add-on Version: N/A (Deprecated)
- Eufy Security Integration Version:

Hardware Information;
- Camera Model: Homebase 3 and Eufy Cam 3. Has issues with other battery cameras as well including Eufy Cam 2. I have tried on Homebase 2 and issue remains.

- Live Streaming Protocol (RTSP/P2P): RTSP and P2P

- Debug Logs from Home Assistant - Usernames/Passwords/Serial Numbers redacted.

[hass_eufy_security_log.txt](https://github.com/fuatakgun/eufy_security/files/13744600/hass_eufy_security_log.txt)

- Would you share your device with me in case further debugging required? (Yes/No): Yes

**Additional context**

As mentioned previously, I believe the error may be coming from either go2rtc or WebRTC, so it may need to be raised in one of those projects. But it also may be an integration issue, so I was hoping it could be looked into here first. 

I will be sure to buy a coffee for the help. Thanks!

**Comment by braddunlap** [comment]
I noticed that the camera entities / streams are not getting added to go2rtc unless I add the card with a manual URL. Then the RTSP URLs will show in go2rtc and I can click and view the stream. I think that may be part of the issue and I am wondering how the integration with go2rtc is supposed to work and if I should be seeing all of my camera IDs in go2rtc. Currently this is not working.

**Comment by radeon79** [comment]
I have same problem with all my eufy camera.

**Comment by braddunlap** [comment]
Looks like @fuatakgun just dropped a major update (version 8.0.0) just a few hours ago. But it has a breaking dependency on a new version of go2rtc that has yet to be released, which hopefully will be released soon. Check out the build notes for more info. I am hoping this will be fixed in the new version once it is available.

**Comment by fuatakgun** [comment]
Please get webrtc from my fork following readme. It has respective dependency

**Comment by braddunlap** [comment]
> Please get webrtc from my fork following readme. It has respective dependency

Thanks. It's working better at least for RTSP cameras, but I am now having a new issue with trying to edit the configuration of Eufy Security Integration. It's throwing an error - Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

I'll log a new bug so you can close this one.

**Comment by data-alchemist** [comment]
Hi, I am new to HA. I have set local Tuya, some water, temp sensors, door locks and now the Eufy cameras. I have received this error too.

I am using home base 2, dual cam doorbell and a bunch of wifi flood light cam and flood light pro. When I use stock HA camera entity card, it shows picture of the last event detected (unreliably). Also, the picture of the last event is a couple of days old sometimes (this is the stock card, not custom webrtc card).

WebRTC card does not start stream and shows Can't get URL for camera.backyard.

Is there an update or debug that I can try?

**Comment by geidorei** [comment]
Same happening with me to.

**Comment by deifel** [comment]
Same problem here

**Comment by zalewskigrzegorz** [comment]
got this same issue this is my code:
```
square: false
type: grid
columns: 1
cards:
  - type: entities
    entities:
      - entity: switch.salon_camera_enabled
        name: Camera enabled
      - entity: select.salon_guard_mode
        name: Guard Mode
      - entity: binary_sensor.salon_crying_detected
        name: Crying detected
      - entity: sensor.salon_current_mode
        name: Current Mode
      - entity: binary_sensor.salon_debug_device
        name: Debug (device)
      - entity: binary_sensor.salon_debug_station
        name: Debug (station)
      - entity: binary_sensor.salon_motion_detected
        name: Motion detected
      - entity: binary_sensor.salon_person_detected
        name: Person detected
      - entity: sensor.salon_person_name
        name: Person Name
      - entity: binary_sensor.salon_pet_detected
        name: Pet detected
      - entity: binary_sensor.salon_snooze
        name: Snooze
      - entity: sensor.salon_snooze_time
        name: Snooze Time
      - entity: binary_sensor.salon_sound_detected
        name: Sound detected
    title: Salon
  - type: alarm-panel
    entity: alarm_control_panel.salon
  - type: custom:webrtc-camera
    entity: camera.salon
    ptz:
      service: eufy_security.ptz
      data_left:
        entity_id: camera.salon
        direction: LEFT
      data_right:
        entity_id: camera.salon
        direction: RIGHT
      data_up:
        entity_id: camera.salon
        direction: UP
      data_down:
        entity_id: camera.salon
        direction: DOWN
```
        
and result:
        
![Arc_2024-03-17_11 57_bnrVkdK6](https://github.com/fuatakgun/eufy_security/assets/12560152/09a4c839-9965-4a5c-b4fe-c4cc43e310b4)
Add-on is working, i can switch camera on and off

**Comment by sysofwan** [comment]
I had the same issue. It was fixed by setting the camera’s streaming quality to low.

**Comment by data-alchemist** [comment]
> I had the same issue. It was fixed by setting the camera’s streaming quality to low.

@sysofwan, did you make any other change? I tried changing stream quality to low but made no difference. My card code is below. I have tried with a simpler, first two lines from the card as well.

```
type: custom:webrtc-camera
entity: camera.backyard
poster: image.backyard_event_image
ui: false
shortcuts:
  - name: Play
    icon: mdi:play
    service: camera.turn_on
    service_data:
      entity_id: camera.backyard
  - name: Stop
    icon: mdi:stop
    service: camera.turn_off
    service_data:
      entity_id: camera.backyard
```

**Comment by sysofwan** [comment]
Make sure the recording quality is also low. Also I find that sometimes I have to reload the page for steaming to start.

**Comment by data-alchemist** [comment]
> Make sure the recording quality is also low. Also I find that sometimes I have to reload the page for steaming to start.

Lowest I can set is 1080p and I have set that. No luck still.

**Comment by tomneij** [comment]
same issue here, set my quality to 720 but no lock either

**Comment by Clem-** [comment]
Same issue. I get @fuatakgun webrtc-camera card fork, my camera have RTSP disabled (otherwise motion detection is not working), and I always have this error:
`Error requesting stream: camera.xxx does not support play stream service`

The poster image isn't even displayed when streaming's off.

The thing is, I don't have an option to change streaming quality for my 2C cameras.

**Comment by cong-khai-nguyen** [comment]
> I had the same issue. It was fixed by setting the camera’s streaming quality to low.

This works for me. I was constantly getting: Can't get URL for camera.doorbell in my dashboard while the stream would work fine on go2rtc

**Comment by EthanMendel** [comment]
I'm also having this issue - Camera quality is set to low. Attached are my logs: [home-assistant.log](https://github.com/user-attachments/files/16716163/home-assistant.log)

**Comment by cracyfloyd** [comment]
Here the same.
I am very fresh with homeassist.
i am come from iobroker and homekit. (for years). in this i have not any problems with the integration of the eufy.doorbell. it works every time well.

**Comment by EthanMendel** [comment]
Seems like the most recent error stack is:
```Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webrtc/__init__.py", line 256, in get
    return await ws_poster(hass, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webrtc/__init__.py", line 207, in ws_poster
    image_entity = _get_image_from_entity_id(hass, poster)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webrtc/__init__.py", line 188, in _get_image_from_entity_id
    raise Exception("Image not found")
Exception: Image not found
```

**Comment by casperleenheer** [comment]
I have the same issue. However I did notice something. I have a webrtc camera defined:

```
  - type: custom:webrtc-camera
    entity: camera.carport_2
    poster: image.carport_event_image
    ui: true
    shortcuts:
      - name: Play
        icon: mdi:play
        service: camera.turn_on
        service_data:
          entity_id: camera.carport_2
      - name: Stop
        icon: mdi:stop
        service: camera.turn_off
        service_data:
          entity_id: camera.carport_2
```

With the above I always have the Can't get URL issue. Now I add the same camera as follows:

```
  - type: picture-entity
    entity: camera.carport_2
    stream_source: rtsp://127.0.0.1:8554/T8600XXXXXXXXX
    authentication: basic
    camera_view: live
    show_state: true
    aspect_ratio: 16x9
```

I refresh the dashboard: I still have the error. Now I press the play button and the picture-entity eventually shows streaming, although no moving pictures. Now I refresh the dashboard again and voila the webrtc camera is running and most of the times the picture-entity also. Is this already known and/or useful?
