### ISSUE TITLE
Add-On Crashing multiple times per day

### ISSUE THREAD

**Issue by ejpenney** [fuatakgun/eufy_security#1089]
No rhyme or reason, network connection to the video doorbell is strong, plenty of resources for the Add-On and Home Assistant.  Everything works, except that it's dumping notifications sometimes 30-40 times per day and everything Eufy stops working until I restart the Add-On (not reloading the integration, restarting the add-on)  The crashes cluster, it'll happen 5-10 times in an hour, then be okay for a few hours.

![image](https://github.com/fuatakgun/eufy_security/assets/21226768/e72f4e31-6131-486d-8188-1fed52ea7a53)
(these retries never succeed)

**To reproduce**

1. Install everything as described
2. Wait...(could be a few minutes or a few hours)
3. Eufy Add-On will inevitably crash

**Expected behavior**

It shouldn't crash.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Home Assistant OS
- Home Assistant Core Version: 2023.12.1
- Eufy Security Add-on Version: 1.7.1
- Eufy Security Integration Version: 8.0.1 (also verified present with 7.7.4)
- WebRTC: https://github.com/fuatakgun/WebRTC/commit/e875efca3fc59d23aa062f3109add6f0e48f1d78

Hardware Information;
- Camera Model: T8203

- Live Streaming Protocol (RTSP/P2P): P2P

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  
[home-assistant_eufy_security_2024-01-18T18-01-42.540Z.log](https://github.com/fuatakgun/eufy_security/files/13980969/home-assistant_eufy_security_2024-01-18T18-01-42.540Z.log)

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

[402f1039_eufy_security_ws_2024-01-18T18-02-04.616Z.log](https://github.com/fuatakgun/eufy_security/files/13980970/402f1039_eufy_security_ws_2024-01-18T18-02-04.616Z.log)

- Would you share your device with me in case further debugging required? (Yes/No):
Yes

**Additional context**

I grabbed these logs 1-2 minutes after a crash, but unfortunately it looks like Home Assistant truncates Add-On logs.  When debug is disabled for Add-On nothing appears in the logs, it's possible there's a message earlier, but if so I didn't find it.

Only thing I can think that might be remotely relevant, is I have some automations that start/stop the doorbell stream a few times a day.  In a few words, I hate the "event images", they're grainy, and badly cropped.  So basically during doorbell events, and once an hour I start a stream and use eufy_security.generate_image to create a better looking image for the stream preview.  I have tried disabling these automations but it doesn't seem to make a difference for stability.

**Comment by OskarLebuda** [comment]
same issue here

**Comment by ZogKarndon** [comment]
I'm having the same issues as well.

**Comment by eufysecurity** [comment]
This happens when when turning on p2p streaming sometimes. You have to restart the add-on for it to be able to connect again.

**Comment by mheiker** [comment]
same problem!

**Comment by ejpenney** [comment]
I have this automation which will restart the add-on when Eufy devices become unavailable, then reload the integration if the integration doesn't recover automatically:

```
alias: "Fix: Eufy Add-On Crash"
description: ""
trigger:
  - platform: state
    entity_id:
      - switch.doorbell_audio_recording
    to: unavailable
    for:
      hours: 0
      minutes: 1
      seconds: 0
    from: null
condition: []
action:
  - service: hassio.addon_restart
    data:
      addon: 402f1039_eufy_security_ws
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - if:
      - condition: state
        entity_id: switch.doorbell_audio_recording
        state: unavailable
    then:
      - service: homeassistant.reload_config_entry
        data: {}
        target:
          device_id: c2df091b9b6a0023c709f367e6626cde
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
mode: restart
```

After I generated those logs last week it started firing every 2 minutes, the Integration couldn't maintain a connection to the Add-On period.  It basically went into a loop.  I tried restarting everything, deleting, re-insatlling... Then I reverted back to integration 7.7.4 and the [upstream RTC](https://github.com/AlexxIT/WebRTC/releases/tag/v3.5.1) and everything started working again (no change to the Add-On or version).  3 days now with no crashes.

I suspect it's either the customized RTC or the Integration.
