### ISSUE TITLE
webRTC streams not working

### ISSUE THREAD

**Issue by domb84** [fuatakgun/eufy_security#1111]
When I attempt to start and stream a webRTC stream, the codec appears to be invalid.

The stream starts and navigating to the go2rtc web ui and getting the stream info shows a valid stream:

`{
  "producers": [
    {
      "url": "T8142N93214313EB"
    },
    {
      "type": "Bitstream producer",
      "medias": [
        "video, recvonly, H.264 High 4.2"
      ],
      "receivers": [
        "255 H264, bytes=598262, senders=1"
      ],
      "recv": 608321
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://192.168.0.11:8554/T8142N93214313EB",
      "remote_addr": "192.168.0.11:59630",
      "user_agent": "Lavf60.3.100",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=64002a;sprop-parameter-sets=J2QAKq0AzoB4AiflmoCAgPgAAAMACAAAAwDxoAAQRAABhmG//4FA,KO48sA==\r\na=control:trackID=0\r\n",
      "medias": [
        "video, sendonly, ANY",
        "audio, sendonly, ANY"
      ],
      "senders": [
        "96 H264, bytes=380376, receivers=1"
      ],
      "send": 397572
    }
  ]
}`

Playing it in the go2rtc web ui using the standard stream.html i get  this error:

`undefined error=streams: codecs not matched: H264 => JPEG caller=github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166`

If I select any of the rtsp streams i.e. rtsp://192.168.0.11:8554/T8142N93214313EB, i can playback without issue in VLC, so the stream is working.

Nothing is ever shown in the home assistant ui when using this card:

```
type: custom:webrtc-camera
entity: camera.back_door
poster: image.entrance_event_image
ui: true
shortcuts:
  - name: Play
    icon: mdi:play
    service: camera.turn_on
    service_data:
      entity_id: camera.back_door
  - name: Stop
    icon: mdi:stop
    service: camera.turn_off
    service_data:
      entity_id: camera.back_door

```
The black image remains there at all times, whether streaming or not.

![image](https://github.com/fuatakgun/eufy_security/assets/14580495/a461918e-ea9e-40e6-8f6b-bd5d28d5df9c)

Am I missing a step? It looks as though it is trying to pull the wrong stream perhaps?
