### ISSUE TITLE
Switch mode to geofencing in gui

### ISSUE THREAD

**Issue by r77s** [fuatakgun/eufy_security#117]
Is it possible to switch with the gui to geofencing? I can only switch from home to away and back.

![2021-11-17 (2)](https://user-images.githubusercontent.com/18601077/142197368-d475bbaf-d081-4da3-8f69-551b0a5455b3.png)

But apart from my question. Great work :-)

**Comment by fuatakgun** [comment]
sadly no, without building a custom frontend card, we are stuck with existing options. Disarmed, armed home, armed away. For the rest, you can use service calls.

**Comment by MechEng70** [comment]
for my case, I use HA geofencing to change from home to away and vice versa.  Use this for simplisafe and eufy.  That way I do not use the eufy app geofencing.  Would that work for you?

**Comment by r77s** [comment]
I activate this addon in my HA. Now I activate "away" at 18:00 and then activate "geofencing" 

> for my case, I use HA geofencing to change from home to away and vice versa. Use this for simplisafe and eufy. That way I do not use the eufy app geofencing. Would that work for you?

I activate this addon in my HA. Now I activate "away" at 18:00 and then activate "geofencing"  at 9:00 in the morning. This works for my use-case.
@MechEng70 : How do you do that? Can you explain your automation?

**Comment by MechEng70** [comment]
Here are my automations: 

For setting it to away mode when both are not home:

```
alias: SentryEye - Set Away
description: ''
trigger:
  - entity_id: group.occupancy
    platform: state
    to: not_home
condition: []
action:
  - data:
      mode: armed_away
    service: aarlo.alarm_set_mode
    entity_id: alarm_control_panel.aarlo_sentryeye
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: alarm_control_panel.alarm_arm_away
    target:
      entity_id: alarm_control_panel.sentryeye
mode: single
```

For setting to home mode when both are home:

```
alias: SentryEye - Set Home
description: ''
trigger:
  - entity_id: group.occupancy
    platform: state
    to: home
condition: []
action:
  - service: alarm_control_panel.alarm_arm_home
    target:
      entity_id: alarm_control_panel.sentryeye
mode: single

```

Set to away mode when the house is set to secure from google (this uses a variable from my ISY hub):

```
alias: SentryEye - Night Time
description: ''
trigger:
  - entity_id: sensor.s_securehome
    platform: state
    from: '0'
    to: '1'
condition: []
action:
  - service: alarm_control_panel.alarm_arm_away
    target:
      entity_id: alarm_control_panel.sentryeye
mode: single
```

This resets the system to home mode at 5am.  I am looking to change this to when my phone alarm is dismissed and I am home: 

```
alias: SentryEye - Early Morning Reset
description: ''
trigger:
  - platform: time
    at: '05:00:00'
condition:
  - condition: state
    entity_id: group.occupancy
    state: home
action:
  - service: alarm_control_panel.alarm_arm_home
    target:
      entity_id: alarm_control_panel.sentryeye
mode: single
```
