### ISSUE TITLE
Support for Doorbell C31

### ISSUE THREAD

**Issue by wolfjank** [fuatakgun/eufy_security#1238]
Hello there, i wanted to know of it is possible to get the new C31 Doorbell ready for homeassistant. This would be really really nice. I would spend one more coffee ;-)

**Comment by gazm2k5** [comment]
I just got a C30 doorbell and would also like to see some support added!

In case it's of any use, binary_sensor.doorbell_debug_device returns:

```
properties:
  name: Doorbell
  model: T8224
  serialNumber: T82245102433ACC2
  hardwareVersion: 0.0.0.4
  softwareVersion: 3.0.8.8
  type: 96
  stationSerialNumber: T82245102433ACC2
commands: []
voices: null
friendly_name: Doorbell Debug (device)
```

And the station:
```
properties:
  name: Doorbell
  model: T8224
  serialNumber: T82245102433ACC2
  type: 96
  hardwareVersion: 0.0.0.4
  softwareVersion: 3.0.8.8
  connected: false
commands: []
voices: null
friendly_name: Doorbell Debug (station)
```
