### ISSUE TITLE
T8530 Camera Stream not working

### ISSUE THREAD

**Issue by chrisgali1968** [fuatakgun/eufy_security#1277]
### Device Details:
- Camera Model: **Eufy Smart Lock with Wi-Fi Bridge and Doorbell Chime - T8530**
- Live Streaming Protocol (RTSP/P2P): **P2P**

### Home Assistant Details:
- **Virtual Machine on Synology NAS**
- Home Assistant Installation Type (OS - Supvervised - Core): **Home Assistant OS**
- Home Assistant Core Version: **core-2024.12.5**
- Eufy Security Add-on Version: **1.9.1**
- Eufy Security Integration Version: **8.1.1**
- Using go2rtc Add-on or webrtc custom integration with integrated go2rtc: **webrtc custom integration with integrated go2rtc**

### Steps followed (same numbers as your installation guide):

**1. Installing Eufy Security Add-On**
- Name: eufy-security-ws
- Version: 1.9.1
- Start on boot: on
- Watchdog: on
- Auto update: om
- Hostname: 402f1039-eufy-security-ws
- Add-on CPU usage: 0.1%
- Add-on RAM usage: 2.5%
- Configuration: Settings > Add-On > eufy-security-ws
`username: <my username>`
`password: <my password>`
`country: US`
`port: 3000`
`polling_interval: 10`
`accept_invitations: true`
`debug: false`
`ipv4first: false`
`event_duration: 10`
`stations:`
`- serial_number: <Lock Serial Number>`
`  ip_address: 10.0.0.102`
`- serial_number: <Chime Serial Number>`
`  ip_address: 10.0.0.102`

**2. Install go2rtc Add-on**
- HACS > Integrations > Plus > WebRTC Camera > Install
- Confirmed the following 
- > Integrations: Settings > Devices & Services > WebRTC Camera
           Folder: **/homeassistant/custom_components/webrtc**
           File: **go2rtc-1.9.4**
           Custom Card: **WebRTC Camera**
           **NO "go2rtc.yaml" file present**

**3. Installing Eufy Security Integration**
> 1 - HACS already installed
2 - Found Eufy Security in HACS
3 - Eufy Security Installed (HA restarted)
4 - Settings > Devices & Services > Add Integration > Eufy Security (found)
5 - Settings
     `Host IP Address - 127.0.0.1`
     `Port -  3000`
6 - No Captcha or MFA
7 - Don't know where to do this... *** NOT DONE ***
8 - Configuration
    `Cloud Scan Interval: 600`
    `Host IP Address: 127.0.0.1`
    `(no Port enrty field)` *** NOT AVAILABLE ***
    `(no Video Analzyze field)` *** NOT AVAILABLE ***
    `(no Generate FFMPEG checkbox)` *** NOT AVAILABLE ***
    `Do not use STREAM module...: unchecked`
    `Override Name for Custom1 Guard Mode: Custom 1`
    `Override Name for Custom2 Guard Mode: Custom 2`
    `Override Name for Custom3 Guard Mode: Custom 3`
9 - Changes done for Disabled entities - enabled the following:
    `lock.eufy_smart_lock`
    `sensor.front_door_lock_battery_percentage`
    `sensor.front_door_lock_lock_status`
    `button.front_door_lock_start_p2p_stream`
    `button.front_door_lock_stop_p2p_stream`
    `sensor.front_door_lock_stream_provider`
    `sensor.front_door_lock_stream_status`
    `sensor.front_door_lock_stream_url`

4. Setting up your dashboard for camera
``` yaml
views:
  - title: Home
    background:
      image: /api/image/serve/5c4f779516f02f53edf335a9d1377393/original
    cards: []
    type: sections
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Front Door Lock
            heading_style: subtitle
            badges: []
            icon: mdi:home-lock
          - type: custom:webrtc-camera
            entity: camera.front_door_lock
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: button.front_door_lock_start_p2p_stream
            name: Start Stream
            icon_height: 50px
            icon: mdi:view-stream
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: button.front_door_lock_stop_p2p_stream
            name: Stop Stream
            icon_height: 50px
            icon: mdi:view-stream-outline
          - type: tile
            entity: sensor.front_door_lock_stream_status
            grid_options:
              columns: 12
              rows: 1
      - type: grid
        cards:
          - type: heading
            heading: Diagnostics
            heading_style: subtitle
            badges: []
            icon: ''
          - type: tile
            entity: lock.front_door_lock
            grid_options:
              columns: full
              rows: 1
          - type: tile
            entity: sensor.front_door_lock_battery_percentage
            grid_options:
              columns: full
          - type: tile
            entity: sensor.front_door_lock_lock_status
            grid_options:
              columns: full
          - type: tile
            entity: button.front_door_lock_start_p2p_stream
            grid_options:
              columns: full
          - type: tile
            entity: button.front_door_lock_stop_p2p_stream
            grid_options:
              columns: full
          - type: tile
            entity: sensor.front_door_lock_stream_provider
            grid_options:
              columns: full
          - type: tile
            entity: sensor.front_door_lock_stream_status
            grid_options:
              columns: full
          - type: tile
            entity: sensor.front_door_lock_stream_url
            grid_options:
              columns: full
        column_span: 1
      - type: grid
        cards:
          - type: heading
            heading: Sensors
            heading_style: subtitle
          - type: tile
            entity: camera.front_door_lock
            show_entity_picture: true
            grid_options:
              columns: full
          - type: tile
            entity: binary_sensor.front_door_lock_debug_device
            grid_options:
              columns: full
          - type: tile
            entity: image.front_door_lock_event_image
            show_entity_picture: true
            grid_options:
              columns: full
          - type: tile
            entity: binary_sensor.front_door_lock_motion_detected
            grid_options:
              columns: full
          - type: tile
            entity: binary_sensor.front_door_lock_person_detected
            grid_options:
              columns: full
          - type: tile
            entity: sensor.front_door_lock_person_name
            grid_options:
              columns: full
          - type: tile
            entity: binary_sensor.front_door_lock_ringing
            grid_options:
              columns: full
          - type: tile
            entity: binary_sensor.front_door_lock_snooze
            grid_options:
              columns: full
          - type: tile
            entity: sensor.front_door_lock_snooze_time
            grid_options:
              columns: full
          - type: tile
            entity: binary_sensor.front_door_lock_someone_loitering
            grid_options:
              columns: full
      - type: grid
        cards:
          - type: heading
            heading: Configuration
            heading_style: subtitle
          - type: tile
            entity: switch.front_door_lock_audio_recording
            grid_options:
              columns: full
          - type: tile
            entity: switch.front_door_lock_auto_nightvision
            grid_options:
              columns: full
          - type: tile
            entity: number.front_door_lock_homebase_chime_ringtone_volume
            grid_options:
              columns: full
          - type: tile
            entity: switch.front_door_lock_indoor_chime_enabled
            grid_options:
              columns: full
          - type: tile
            entity: switch.front_door_lock_loitering_detection
            grid_options:
              columns: full
          - type: tile
            entity: switch.front_door_lock_motion_detection
            grid_options:
              columns: full
          - type: tile
            entity: select.front_door_lock_motion_detection_type
            grid_options:
              columns: full
          - type: tile
            entity: number.front_door_lock_speaker_volume
            grid_options:
              columns: full
          - type: tile
            entity: select.front_door_lock_video_recording_quality
            grid_options:
              columns: full
          - type: tile
            entity: select.front_door_lock_video_streaming_quality
            grid_options:
              columns: full
```

![Cards](https://github.com/user-attachments/assets/2a12b771-e000-452e-8a3d-fc4582e450e5)
[402f1039_eufy_security_ws_2024-12-31T04-35-01.293Z.log](https://github.com/user-attachments/files/18279414/402f1039_eufy_security_ws_2024-12-31T04-35-01.293Z.log)
