### ISSUE TITLE
Entities not getting updated

### ISSUE THREAD

**Issue by Ofir-P** [fuatakgun/eufy_security#1313]
Hey!
I was following the guide of fuatakgun https://github.com/fuatakgun/eufy_security?tab=readme-ov-file#how-is-this-working
I finally got the entities showing up in my Home Assistant.

However, if my doorbell for instance ringing (someone at the door) the image entity not getting updated (unlike the app where I can see the thumbnail of the last motion detected)

I do get the entity state changed in case someone presses the doorbell
BUT not getting state changed for other entities like motion detected and so on.

If I enable P2P stream I can see the live footage of the camera 
by doing this
```
type: custom:webrtc-camera
entity: camera.doorbell
poster: image.doorbell_event_image
ui: true
shortcuts:
  - name: Play
    icon: mdi:play
    service: button.press
    service_data:
      entity_id: button.doorbell_start_p2p_stream
  - name: Stop
    icon: mdi:stop
    service: button.press
    service_data:
      entity_id: button.doorbell_stop_p2p_stream

```

Here are my 2nd account app settings for the doorbell camera (it won't let me take a screenshot so I'm writing it down) - 
Motion Detection - 
Motion Detection - on
Detection type - human recognition & human detection on
Sensitivity - medium

Video quality-
Streaming quality medium
video encoding - low
wdr enabled - off

Notifications -
Motion detect - on
doorbell ring - on

What am I missing here?
