### ISSUE TITLE
No audio from P2P stream?

### ISSUE THREAD

**Issue by MastaG** [fuatakgun/eufy_security#1348]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

If you are asking for device support, please check `Supported Devices List in eufy-security-client` (https://bropat.github.io/eufy-security-client/#/supported_devices) first. Your device should be listed there with specific device model number, not device name. You can have similar model names but the support is handled by device model number (TXXXX).

**Describe the bug**
I'm not getting audio from my Doorbell.
I have added my doorbell using the example:
```
type: custom:webrtc-camera
entity: camera.deurbel
media: video,audio
poster: image.deurbel_event_image
ui: true
shortcuts:
  - name: Play
    icon: mdi:play
    service: camera.turn_on
    service_data:
      entity_id: camera.deurbel
  - name: Stop
    icon: mdi:stop
    service: camera.turn_off
    service_data:
      entity_id: camera.deurbel
```
I've configured the plugin to use go2rtc which is shiping with Frigate.
Video works fine when I try and play it locally using mpv.
`rtsp://192.168.x.x:8554/T821451024144503?mp4`
However I'm not receiving any audio?

According to the go2rtc web-interface, it only seems to receive a video stream from the source:
```
0	
url	"T821451024144503"
1	
type	"Bitstream producer"
medias	
0	"video, recvonly, H.264 High 5.0"
receivers	
0	"255 H264, bytes=53929054, senders=2"
recv	55703330
```

Would it be possible to also get audio as well?
Also would it be possible to automatically start the stream when Home Assistant starts?
I'm only planning on using my doorbell cam with Frigate.

**To reproduce**

**Expected behavior**

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Core
- Home Assistant Core Version: 2025.5.3
- Eufy Security Add-on Version: v8.2.1
- Eufy Security Integration Version:
- Using go2rtc Add-on or webrtc custom integration with integrated go2rtc: webrtc with custom integration

Hardware Information;
- Camera Model: E340 

- Live Streaming Protocol (RTSP/P2P): P2P

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging required? (Yes/No): yes

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by MastaG** [comment]
Ah thanks a lot, that clears things up.
Also not related to this bug.
Would it be possible to somehow automate starting the stream?
I primarly use it with Frigate to play around with the TPU.
I don't really use home assistant for anything else, besides pressing the play button so I can stream it into Frigate.

**Comment by MastaG** [comment]
Yeah it skips a few frames every now and then, but thats about it.
Just make sure that you:
- Have your doorbell cam wired using a powerful adapter. (a few amps more wouldn't hurt)
- Have your Wireless AP nearby, personally I use the homebase which is wires to Ethernet, which is just a few meters away from the door.

It works really really well, here's my frigate config with the Coral USB thing:

```
mqtt:
  enabled: false

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

snapshots:
  enabled: True
  retain:
    default: 30

cameras:
  name_of_your_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.x.x:9554/T821451024144503?mp4 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1600
      height: 2200
      fps: 5

version: 0.15-1
```

I've switched to WebRTC's embedded go2rtc implementation, instead of the one from frigate, otherwise both frigate and home assistant will depend on each other.

For the home assistant container I mapped the following extra ports:
(host to container)
2084 -> 1984 tcp
9554 -> 8554 tcp/udp
9555 -> 8555 tcp/udp

So in Frigate, I just open the stream from 9554 instead.

When I have time I'll play some more with home assistant, but for now it acts as a P2P -> RTSP bridge :)
