### ISSUE TITLE
Camera Battery

### ISSUE THREAD

**Issue by jconn7** [fuatakgun/eufy_security#146]
Is there a way to request the current battery level of the camera? I have had to charge more and more as my cameras age and I wanted to implement a warning about battery level or battery drain. I know you can get it for the doorbell but I can't find an attribute/entity for battery level in cameras. Thanks!

**Comment by fuatakgun** [comment]
If your camera supports/exposes battery attribute, corresponding sensors should be created automatically.

I have multiple 2c cameras and I have this sensor.

![image](https://user-images.githubusercontent.com/11085566/144295459-d6a8029e-c330-48a9-8e04-37c00d389263.png)

**Comment by jconn7** [comment]
> If your camera supports/exposes battery attribute, corresponding sensors should be created automatically.
> 
> I have multiple 2c cameras and I have this sensor.
> 
> ![image](https://user-images.githubusercontent.com/11085566/144295459-d6a8029e-c330-48a9-8e04-37c00d389263.png)

That's really interesting. I have two 2's and don't have a battery sensor. 
![Eufy Battery](https://user-images.githubusercontent.com/93835497/144296883-281a2d1b-cd14-482a-ac68-9e6374aef584.png)

**Comment by fuatakgun** [comment]
please share your camera state from developer tools

```
inherited:
  type: DEVICE_TYPE.CAMERA2C
  category: CAMERA
  state:
    name: Entrance
    model: T8113-Z
    serialNumber: T8113N63205014E2
    hardwareVersion: T8113-Z
    softwareVersion: 5.4.5
    stationSerialNumber: T8010N2320460480
    enabled: true
    state: 1
    battery: 98
    batteryTemperature: 23
    lastChargingDays: 1
    lastChargingTotalEvents: 344
    lastChargingRecordedEvents: 178
    lastChargingFalseEvents: 166
    batteryUsageLastWeek: 0
    motionDetected: false
    personDetected: false
    personName: ''
    antitheftDetection: false
    motionDetection: true
    rtspStream: true
    watermark: 2
    wifiRSSI: -45
    pictureUrl: >-
      https://zhixin-security-eu.s3.eu-central-1.amazonaws.com/xxx
    type: 8
    motionDetectionType: 0
    light: false
    microphone: true
    speaker: true
    speakerVolume: 93
    audioRecording: true
    powerSource: 0
    powerWorkingMode: 1
    recordingEndClipMotionStops: true
    recordingClipLength: 60
    recordingRetriggerInterval: 5
    lightSettingsBrightnessManual: 100
    notificationType: 1
    motionDetectionSensitivity: 4
    statusLed: false
    rtspStreamUrl: rtsp://admin:admin@192.168.178.34/live1
    chargingStatus: 2
    wifiSignalLevel: 4
    nightvision: 1
    p2pLiveStreamingStatus: livestream stopped
    rtspLiveStreamingStatus: false
    wifiRssi: -42
  properties:
    name:
      value: Entrance
      timestamp: 1638199320000
    model:
      value: T8113-Z
      timestamp: 1638199320000
    serialNumber:
      value: T8113N63205014E2
      timestamp: 1638199320000
    type:
      value: 8
      timestamp: 1638199320000
    hardwareVersion:
      value: T8113-Z
      timestamp: 1638199320000
    softwareVersion:
      value: 5.4.3
      timestamp: 1632837730000
    stationSerialNumber:
      value: T8010N2320460480
      timestamp: 1638199320000
    rtspStreamUrl:
      value: rtsp://admin:admin@192.168.178.34/live1
      timestamp: 1638199358162
    lastChargingDays:
      value: 1
      timestamp: 1638390778000
    lastChargingFalseEvents:
      value: 109
      timestamp: 1638396325000
    lastChargingRecordedEvents:
      value: 102
      timestamp: 1638396325000
    lastChargingTotalEvents:
      value: 211
      timestamp: 1638396325000
    batteryUsageLastWeek:
      value: 0
      timestamp: 1638199320000
    pictureUrl:
      value: >-
        https://zhixin-security-eu.s3.eu-central-1.amazonaws.com/xxx
      timestamp: 1638396313000
    recordingClipLength:
      value: 60
      timestamp: 1638199357839
    recordingRetriggerInterval:
      value: 5
      timestamp: 1638199357839
    recordingEndClipMotionStops:
      value: true
      timestamp: 1638199357839
    lightSettingsBrightnessManual:
      value: 100
      timestamp: 1638199357839
    antitheftDetection:
      value: false
      timestamp: 1637785525000
    rtspStream:
      value: true
      timestamp: 1637785525000
    motionDetection:
      value: true
      timestamp: 1637785525000
    nightvision:
      value: 1
      timestamp: 1637785525000
    enabled:
      value: true
      timestamp: 1637785525000
    chargingStatus:
      value: 2
      timestamp: 1638346484346
    powerSource:
      value: 0
      timestamp: 1637785525000
    speaker:
      value: true
      timestamp: 1637785525000
    microphone:
      value: true
      timestamp: 1637785525000
    battery:
      value: 100
      timestamp: 1638349309158
    watermark:
      value: 2
      timestamp: 1637785525000
    state:
      value: 1
      timestamp: 1637785525000
    audioRecording:
      value: true
      timestamp: 1637785525000
    motionDetectionSensitivity:
      value: 4
      timestamp: 1637785525000
    light:
      value: false
      timestamp: 1637792969000
    speakerVolume:
      value: 93
      timestamp: 1637785525000
    notificationType:
      value: 1
      timestamp: 1637785525000
    powerWorkingMode:
      value: 1
      timestamp: 1637785525000
    statusLed:
      value: false
      timestamp: 1637785525000
    batteryTemperature:
      value: 23
      timestamp: 1638342642949
    motionDetectionType:
      value: 0
      timestamp: 1637785525000
    wifiRssi:
      value: -45
      timestamp: 1638379579611
    wifiSignalLevel:
      value: 4
      timestamp: 1637785525000
    motionDetected:
      value: false
      timestamp: 0
    personDetected:
      value: false
      timestamp: 1638396327108
    personName:
      value: ''
      timestamp: 1638396327108
custom:
  is_streaming: false
  stream_source_type: null
  stream_source_address: null
  codec: h264
  is_rtsp_streaming: false
  is_p2p_streaming: false
friendly_name: Entrance
entity_picture: >-
  /api/camera_proxy/camera.entrance?token=xxx
supported_features: 3
```
