### ISSUE TITLE
Indoor chime switch not working?

### ISSUE THREAD

**Issue by Zeunas** [fuatakgun/eufy_security#164]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
New add-on update (ff37f61) introduced an Indoor Chime switch which I assume is to turn on/off the chime ring after the doorbell button is pressed, however it does nothing. It's always off, regardless and switching on or off, doesn't really change the indoor chime on/off option on the app.

**To Reproduce**
Switch on/off Indoor Chime switch and observe behaviour on the app.

**Expected behavior**
I'd expect to be able to control Indoor chime ring behaviour ie. on or off.

**Screenshots**
![image](https://user-images.githubusercontent.com/71456261/145963257-b35a4133-b619-4c5d-9ec5-54672dfe3bd9.png)

**Hardware Information about Home Assistant
Raspberry pi4

**Hardware Information about Cameras
- Battery Doorbell 2

**Comment by fuatakgun** [comment]
can you also check if it is changing in the app when you turn on in home assistant?

**Comment by Zeunas** [comment]
No, not changes in the app. There's nothing on the logs either. All the other new switches such as Status Led and Motion detection are working perfectly.

**Comment by Zeunas** [comment]
New version (1.0.0) now seems to make some more log errors available. This is what comes up when I try to toggle Indoor chime switch or even Auto night vision switch:

`2021-12-14 22:45:15.291  WARN Station T8020P1021260B39 - Command aged out from queue 
{
  commandType: 1703,
  nestedCommandType: undefined,
  channel: 0,
  ageing: 48864,
  maxAgeing: 45000
}
2021-12-14 22:49:10.221  WARN Station T8020P1021260B39 - Command aged out from queue 
{
  commandType: 1703,
  nestedCommandType: undefined,
  channel: 0,
  ageing: 283643,
  maxAgeing: 45000
}
2021-12-14 22:49:24.334  WARN Station T8020P1021260B39 - Command aged out from queue 
{
  commandType: 1703,
  nestedCommandType: undefined,
  channel: 0,
  ageing: 297605,
  maxAgeing: 45000
}`

**Comment by Zeunas** [comment]
Any updates on this?

**Comment by fuatakgun** [comment]
Will focus soon, just need some time

**Comment by fuatakgun** [comment]
can you double check with latest changes?

**Comment by fuatakgun** [comment]
nope, still not working, tested locally. can you please create an issue to eufy-security-ws repository?

**Comment by Zeunas** [comment]
Will do!!

**Comment by Zeunas** [comment]
Done. Just on the back of this on the app there is also the option to Snooze Motion or Chime for x amount of time, could it be a possible to make this option available instead with a service call?

**Comment by Zeunas** [comment]
Closing not because it has been fixed but because I have opened the issue with eufy-security-ws [here](https://github.com/bropat/eufy-security-ws/issues/71).

Also, just in case someone is looking for a workaround, I have actually managed it by creating a template switch that set's the volume of the chime to 1 or 26 when I want to switch it off or on, respectively:

![image](https://user-images.githubusercontent.com/71456261/150505886-dd6bc6db-86e1-4e7b-8a00-6b1120864f9e.png)

```
switch:
  - platform: template
    switches:
      doorbell_indoor_chime:
        friendly_name: Chime switch
        value_template: "{{ is_state('select.doorbell_chime_volume', '26') }}"
        turn_on:
          - service: select.select_option
            data:
              option: '26'
            target:
              entity_id: select.doorbell_chime_volume
        turn_off:
          - service: select.select_option
            data:
              option: '1'
            target:
              entity_id: select.doorbell_chime_volume
        icon_template: >-
          {% if is_state('switch.doorbell_indoor_chime', 'on') %}
            mdi:bell
          {% else %}
            mdi:bell-off
          {% endif %}
```

![image](https://user-images.githubusercontent.com/71456261/150506198-75e29eaa-266b-4abd-b895-62937327d24a.png)

**Comment by Zeunas** [comment]
Closing not because it has been fixed but because I have opened the issue with eufy-security-ws [here](https://github.com/bropat/eufy-security-ws/issues/71).

Also, just in case someone is looking for a workaround, I have actually managed it by creating a template switch that set's the volume of the chime to 1 or 26 when I want to switch it off or on, respectively:

![image](https://user-images.githubusercontent.com/71456261/150505886-dd6bc6db-86e1-4e7b-8a00-6b1120864f9e.png)

```
switch:
  - platform: template
    switches:
      doorbell_indoor_chime:
        friendly_name: Chime switch
        value_template: "{{ is_state('select.doorbell_chime_volume', '26') }}"
        turn_on:
          - service: select.select_option
            data:
              option: '26'
            target:
              entity_id: select.doorbell_chime_volume
        turn_off:
          - service: select.select_option
            data:
              option: '1'
            target:
              entity_id: select.doorbell_chime_volume
        icon_template: >-
          {% if is_state('switch.doorbell_indoor_chime', 'on') %}
            mdi:bell
          {% else %}
            mdi:bell-off
          {% endif %}
```

![image](https://user-images.githubusercontent.com/71456261/150506198-75e29eaa-266b-4abd-b895-62937327d24a.png)
