### ISSUE TITLE
Add Docker Compose to documentation

### ISSUE THREAD

**Issue by BinaryShrub** [fuatakgun/eufy_security#245]
You might consider adding a dedicated Docker section that includes Docker compose setup.

I wrote it for you here, feel free to use it:
``` yml
version: '3'
services:
  # Other Services
  # ...
  # Eufy Security Websocket Server
  eufy-security-ws:
    container_name: eufy-security-ws
    image: bropat/eufy-security-ws
    restart: unless-stopped
    environment:
      - USERNAME=<ENTER_EUFY_ACCOUNT_USERNAME_HERE>
      - PASSWORD=<ENTER_EUFY_ACCOUNT_PASSWORD_HERE>
    ports:
      - '3000:3000' # port for Eufy websocket server
```

Also consider adding a note around port collision since 3000 is also used by default in `zwavejs/zwavejs2mqtt`
