### ISSUE TITLE
Doorbell ringing with HomePod in HomeKit 

### ISSUE THREAD

**Issue by pillemats** [fuatakgun/eufy_security#308]
Hi

i am using an eufy 2k wired doorbell and I missed the following feature:

My HomePods won’t ring if somebody push the doorbell! I used homebridge before and there it works fine! 

Maybe it is already a feature ? What should I set up to activate it in HomeKit ?

many thanks

**Comment by Daneish** [comment]
In your Home Assistant configuration.yaml you will need to add the camera with the `linked_doorbell_sensor` and probably the `linked_motion_sensor` too.

Here is what I have in my configuration.yaml file:

````
homekit:
  - name: HA YAML Access Doorbell # Max of 25 characters
    port: 21069 #Port Scan showed this to be free
    mode: accessory
    filter:
      include_entities:
        - camera.front_door_doorbell
    entity_config:
      camera.front_door_doorbell:
        name: Front Door Doorbell
        linked_doorbell_sensor: binary_sensor.front_door_doorbell_ringing_sensor
        linked_motion_sensor: binary_sensor.front_door_doorbell_global_motion_sensor
        stream_source: !secret doorbell_stream_source
````

More info here: https://www.home-assistant.io/integrations/homekit/
