### ISSUE TITLE
Lock state does not update unless it's locked/unlocked by Integration?

### ISSUE THREAD

**Issue by eroji** [fuatakgun/eufy_security#349]
I have a T8510 WiFi lock installed and the integration configured. I added a second account which I shared the lock to and the integration itself is working perfectly. However, noticed that the status on the lock entity does not update to reflect its current state if it's unlocked or locked via app or manually. Only lock/unlock done via Home Assistant is actually logging the state change.

**Comment by NursePinkamena** [comment]
I am also reporting the same issues I am using a T8500 wifi lock.

**Comment by Giotrumpet** [comment]
Same here with T8510 with bridge.

**Comment by fuatakgun** [comment]
did you enable all push notifications as this integration/add-on fully rely on this

**Comment by eroji** [comment]
I assume you mean this @fuatakgun? If it is they're all enabled as you can see. 
![ED1D868E-DC58-4B15-BF75-2B096352AB44](https://user-images.githubusercontent.com/13228540/174903427-8958f093-d569-4762-b168-9aaec0ee194b.png)

**Comment by Giotrumpet** [comment]
Same here, all notifications enabled.

**Comment by jem** [comment]
I have this issue with 3 of the T8510 locks. When I had just one it worked almost all the time, but using 2 or 3 on the same account seems to completely disable the lock state fetching, unless it is locked and unlocked by HA. I tried slimming the account down to just 1, and it was working again, so it is reproducible.

**Comment by jem** [comment]
What is the best way to grab extra logs for this? I am comfortable trying whatever, but if there are any notes for what to enable and where, I would appreciate it!

**Comment by fuatakgun** [comment]
please share your device following README and let me know when I can debug

**Comment by fuatakgun** [comment]
merging threads: https://github.com/fuatakgun/eufy_security/issues/298

**Comment by jem** [comment]
@fuatakgun I shared my device (wood bru) with you. Please leave mostly locked :)

if it doesn’t show problems, you might need access to a second lock too. If so please let me know, although I will need to coordinate when you want ti test.

**Comment by eroji** [comment]
@fuatakgun I don't think the issue is resolved. At least it's still not updating the state with the latest stable release.

**Comment by dmiddlet2005** [comment]
@fuatakgun Lock status not auto updating for me either.  
Home Assistant 2022.7.5
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.1 - latest
Eufy T8510 - Firmware 2.0.2.3

**Comment by jem** [comment]
@fuatakgun great, ping me if you need a second device if things unexpectedly work perfectly

**Comment by jem** [comment]
@fuatakgun also let me know if you need a second account to have access—it works ok when locked/unlocked directly from HA, but it is when a different account or the actual lock operates that HA doesn't update. or I can do some lock/unlock events

**Comment by fuatakgun** [comment]
hey, can we connect over google meet? https://meet.google.com/esb-vdrd-ggz?pli=1

**Comment by jem** [comment]
Per our online debug session, here is the debug line for an unlock event:
`2022-07-27 14:27:36 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - set_event_for_entity - device / T8510Q10212603EB / lockStatus / False`

**Comment by fuatakgun** [comment]
please test with `v2.2.9` of integration

**Comment by jem** [comment]
All sorted, thank you so much! Works nicely with 2.2.9 with both locks.

**Comment by alexeiw123** [comment]
My T8520 lock is no longer after updating the integration today. Prior to this I had issues (#376) while in geolocation mode, so simply turned it off. Now it's happening in home and away modes.

I have a few eufy devices if this could be related (wifi doorbell +home and floodlight cam E 2K)

**Comment by fuatakgun** [comment]
Let's follow over new issue (already created one) and i have requested some help there.

**Comment by fuatakgun** [comment]
@jem , we also need your support on this, is it still working for you? Please get latest integration version, there were some fundamental changes after our workshop.

**Comment by jem** [comment]
> @jem , we also need your support on this, is it still working for you? Please get latest integration version, there were some fundamental changes after our workshop.

Working correctly for me with `2.5.0` and `0.9.3`.

**Comment by fuatakgun** [comment]
@jem can you also do the same exercise above and share your results?

**Comment by fuatakgun** [comment]
Same exercise from #402

**Comment by jem** [comment]
@fuatakgun I looked at the states for `lock.wooden_door` and diffed after unlocking with the app, getting only:
```
> diff {un,}locked
12c12
< lockStatus: false
---
> lockStatus: true
```

Here is a trimmed version of the locked version:
```
type: DEVICE_TYPE.LOCK_BASIC
category: LOCK
state: 
name: Wooden door
model: T8510
hardwareVersion: '1.2'
softwareVersion: 2.0.4.2
state: 1
locked: false
lockStatus: true

properties: 
name: Wooden door
model: T8510
type: 50
hardwareVersion: '1.2'
softwareVersion: 2.0.4.2
state: 1
wifiRssi: -80
wifiSignalLevel: 2
lockStatus: true
locked: false

locked:
  key: custom_locked
  name: locked
  label: locked
  readable: true
  writeable: true
  type: boolean
lockStatus:
  key: 9999
  name: lockStatus
  label: Lock status
  readable: true
  writeable: false
  type: number
  states:
    '1': '1'
    '2': '2'
    '3': Unlocked
    '4': Locked
    '5': Mechanical anomaly
    '6': '6'
    '7': '7'

friendly_name: Wooden door
```
