### ISSUE TITLE
Not finding homebase / eufycam

### ISSUE THREAD

**Issue by gerardsyd** [fuatakgun/eufy_security#369]
**Describe the bug**
Cannot connect integration to homeassistant. 
I have a Eufycam T8210 w/ homebase (video doorbell 2k battery)
I have Home Assistant Core running in docker-compose on Ubuntu Server. Since I'm not running hass / supervisor, I don't have access to add-ons so I have installed eufy-security-ws through docker-compose as below:

```
  eufy-security:
    container_name: eufy_security
    restart: always
    image: bropat/eufy-security-ws:latest
    environment:
      - USERNAME={email}
      - PASSWORD={password}
      - COUNTRY=AU
    network_mode: host
    volumes:
      - ${USERDIR}/docker/shared:/data
```

when I check my docker-compose logs, I get the following:
``` eufy_security    | 2022-06-19T09:22:14.560466889Z 2022-06-19 09:22:14.559  INFO  Eufy Security server listening on host 0.0.0.0, port 3000```

but nothing further, it does not seem to be scanning / finding the eufycam or base.  

If I try to add via HA integrations, it does not find the host. 

**To Reproduce**
1. run docker-compose as per above
2. check docker-compose logs

**Expected behavior**
Find the camera / connect to homebase

**Hardware Information about Home Assistant
I have Home Assistant Core running in docker-compose on Ubuntu Server. Since I'm not running hass / supervisor, I don't have access to add-ons so I have installed eufy-security-ws through docker-compose 

**Hardware Information about Cameras
- Camera Model: Eufycam T8210 

**Additional context**
I've tried disabling Traefik and it still does not connect. It shows it running as above but does not show a connection to the homebase so seems to be an issue there. Have I got my container setup wrong?
