### ISSUE TITLE
Live snapshot

### ISSUE THREAD

**Issue by alexreddy78** [fuatakgun/eufy_security#4]
Hello,

Kindly advise if camera can take live snapshot in HA upon motion detected, using service camera.snapshot and record live video by camera.record?

Best Regards

**Comment by fuatakgun** [comment]
this should work;

```
alias: Motion detected in Entrance, record snapshot
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.entrance_motion_sensor
    to: 'True'
  - platform: state
    entity_id: binary_sensor.entrance_person_detector_sensor
    to: 'True'
condition: []
action:
  - service: camera.snapshot
    target:
      entity_id: camera.entrance
    data:
      filename: >-
        /tmp/entrance_snapshot_automation.jpg
mode: single
```
