### ISSUE TITLE
Add WebRTC & Home Assistant conditional card tips to README.md

### ISSUE THREAD

**Issue by conorlap** [fuatakgun/eufy_security#43]
Just some potentially useful set-up info for people using @fuatakgun & @bropat 's integration/docker container.

You can get the doorbell live stream down to about 2-4 second delay using WebRTC to display the RTSP camera feed using this integration: https://github.com/AlexxIT/WebRTC 
 
**The lovelace card:**
You can add the additional command **mse: false** because quite often it loads the MSE stream then stutters for another second before loading WebRTC but your results may vary:

```
type: custom:webrtc-camera
entity: camera.doorbell
mse: false
```

You can utilize the lovelace conditional card so the WebRTC feed only displays on the dashboard when the camera is actually streaming, example:

```
type: conditional
conditions:
  - entity: camera.doorbell
    state: Streaming - p2p
card:
  type: custom:webrtc-camera
  entity: camera.doorbell
  mse: false
```

For cleanest set-up, you can create another lovelace card which displays the last event detected by the doorbell. This is also a conditional card and this only displays when the camera is NOT streaming video. To activate video, simply click on the picture which triggers _script.eufy_doorbell_rtsp_reload_ that you can create that calls the _eufy_security.stop_livestream_ & _eufy_security.start_livestream_ service. Examples below:

**Conditional card with script call:**
```
type: conditional
conditions:
  - entity: camera.doorbell
    state: Idle
card:
  type: picture-glance
  entities: []
  camera_image: camera.doorbell
  tap_action:
    action: call-service
    service: script.eufy_doorbell_rtsp_reload
    service_data: {}
    target: {}
```

**Livestream Reload Script:** 
```
alias: Eufy Doorbell RTSP Reload
sequence:
  - service: eufy_security.stop_livestream
    target:
      entity_id: camera.doorbell
  - service: eufy_security.start_livestream
    target:
      entity_id:
        - camera.doorbell
mode: single
```

**Comment by conorlap** [comment]
Maybe you have WebRTC leak protection enabled on your browser? I had **WebRTC Control** extension on my browser and had to stop it to allow WebRTC to work.

**Comment by fuatakgun** [comment]
> Nice. I remember I've tried that integration before and ran into issues, not streaming anything, even from their example on their repo. Maybe I'll have to come back to it and give it another go.

I had the same experience, I will give it a try on WebRTC Control extension.

**Comment by TuomasPakkanen** [comment]
This is cool. Had to change the latter card to following due to there being the battery percentage after Idle in the state for me. However, I'm apparently still having some issues with the video working, but I'll comment on the other thread since it's not related to this one. Will try to remember to report here when I get that working if the delay is better for me by using WebRTC.

```
type: conditional
conditions:
  - entity: camera.doorbell
    state_not: Streaming - p2p
card:
  type: picture-glance
  entities: []
  camera_image: camera.doorbell
  tap_action:
    action: call-service
    service: script.eufy_reload
    service_data: {}
    target: {}

```

**Comment by dpomnean** [comment]
I can report that I finally have this working for my wireless doorbell. After giving up I decided to check it out again as I have other cameras that need a good rtsp player. Once I added the HACS integration I needed to also add it to the home assistant integrations. *facepalm*. So my setup is like this. I needed a button system for my wife to easily turn on and off the camera, and then using the conditional card you wrote ( great idea! ) to display the feed. I also have an automation that kills the feed after 2:50 minutes of runtime so it doesn't destroy the battery life.  

![image](https://user-images.githubusercontent.com/17032114/131282719-5c0efad7-5e5c-4391-a57e-483c90132d4e.png)
```
type: horizontal-stack
cards:
  - type: button
    tap_action:
      action: call-service
      service: eufy_security.start_livestream
      service_data: {}
      target:
        device_id: XXX
    name: Stream Doorbell
    icon_height: 100px
    icon: mdi:video
    entity: camera.doorbell
    show_state: true
  - type: button
    tap_action:
      action: call-service
      service: eufy_security.stop_livestream
      service_data: {}
      target:
        device_id: XXX
    name: Stop Doorbell
    icon_height: 100px
    icon: mdi:video-outline
```
