### ISSUE TITLE
Eufy Security Integration missing?

### ISSUE THREAD

**Issue by opax7** [fuatakgun/eufy_security#451]
## Can't find the Eufy Security Integration
I'm new to Home Assistant, but thought I had the basics down. I'm running in Docker and I have all the services up and running which are required, i.e. (eufy-security-ws, rtsp-simple-server, ffmpeg integration). But I don't know how to get the actual integration setup.

The documentation says to go to "HACS" and search for 'Eufy Security'. In the Docker deployment of HA I don't see any place to install custom repositories. Is that the missing piece? If not, how do I setup the integration?

**docker-compose.yml**
```
version: '3'
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: "homeassistant"
    restart: unless-stopped
    privileged: true
    environment:
      TZ: "America/Chicago"
    volumes:
      - ha-data:/config
    ports:
      - 8123:8123
  eufysecurityws:
    image: "bropat/eufy-security-ws:0.9.4"
    container_name: "eufysecurityws"
    restart: unless-stopped
    environment:
      COUNTRY: "US"
      USERNAME: "***"
      PASSWORD: "***"
      ACCEPT_INVITATIONS: "true"
    volumes:
      - es-data:/data
    ports:
      - 3000:3000
  rtspserver:
    image: aler9/rtsp-simple-server:v0.20.0
    container_name: "rtspserver"
    restart: unless-stopped
    environment:
      RTSP_PROTOCOLS: "tcp"
    ports:
      - 8554:8554
      - 1935:1935
volumes:
  ha-data:
  es-data:
```

All seems to be working....
```
rtspserver    | 2022/09/02 22:57:19 INF rtsp-simple-server v0.20.0
rtspserver    | 2022/09/02 22:57:19 INF [RTSP] listener opened on :8554 (TCP)
rtspserver    | 2022/09/02 22:57:19 INF [RTMP] listener opened on :1935
rtspserver    | 2022/09/02 22:57:19 INF [HLS] listener opened on :8888
eufysecurityws  | 2022-09-02 22:57:20.211  INFO  Eufy Security server listening on host 0.0.0.0, port 3000
eufysecurityws  | 2022-09-02 22:57:30.648  INFO  Push notification connection successfully established
eufysecurityws  | 2022-09-02 22:57:30.728  INFO  Connected to station T*** on host 10.0.*** and port 19851
eufysecurityws  | 2022-09-02 22:57:30.732  INFO  Connected to station T*** on host 10.0.*** and port 19851
homeassistant   | s6-rc: info: service s6rc-oneshot-runner: starting
homeassistant   | s6-rc: info: service s6rc-oneshot-runner successfully started
homeassistant   | s6-rc: info: service fix-attrs: starting
homeassistant   | s6-rc: info: service fix-attrs successfully started
homeassistant   | s6-rc: info: service legacy-cont-init: starting
homeassistant   | s6-rc: info: service legacy-cont-init successfully started
homeassistant   | s6-rc: info: service legacy-services: starting
homeassistant   | services-up: info: copying legacy longrun home-assistant (no readiness notification)
homeassistant   | s6-rc: info: service legacy-services successfully started
```
