### ISSUE TITLE
Preview in notifications not working any more

### ISSUE THREAD

**Issue by eikowagenknecht** [fuatakgun/eufy_security#453]
**Describe the bug**
Hey! I'm using your integration together with the official HA iPhone App and use it to show a notification on my phone when a movement was detected. For the last few months (yeah it's been taking me a while to follow up on this) the preview image does not show any more. This worked fine before.

So what I get is this (fine):
![image](https://user-images.githubusercontent.com/1475672/188385527-8beac311-aa01-4b4f-8bf2-b5851ab78ce1.png)

But when I maximize the notification it shows like this:

![image](https://user-images.githubusercontent.com/1475672/188385632-dd25041c-4e7e-4d50-bbf0-c053b3b1f7de.png)

The same behaviour is on my apple watch (error messag shown).

HLS Stream not available. URLSessionTask failed with error.

**Expected behavior**
Bigger image in maximized notification.
plain your problem.

**Hardware Information about Home Assistant
Lates HA beta, but has been this way for some releases now.

**Hardware Information about Cameras
- Various Eufy battery powered cameras

**Config of the notification
```
...
  data:
    entity_id: camera.au_terrasse_kamera
    tag: kamera_terrasse
    url: lovelace-haussteuerung/sicherheit
    push:
      interruption-level: time-sensitive
...
```
