### ISSUE TITLE
Friendly names for custom modes

### ISSUE THREAD

**Issue by kauthmbt** [fuatakgun/eufy_security#486]
I am looking for a way to create more user-friendly visible names within HA for the modes "custom 1", "custom 2" & "custom 3".

For example in the custom component for Arlo there is a similar way by adjusting the _configuration.yaml_ like this:
```
alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: 'custom 1'
    somethingelse_mode_name: 'custom 2'
    night_mode_name: 'custom 3'
```

This also reflects the readable status in the logging history and in the panel:
![image](https://user-images.githubusercontent.com/74350030/195787471-c22f2bdb-a694-4a0a-a19b-2e3db67d9fec.png)

Instead of the current display:
![image](https://user-images.githubusercontent.com/74350030/195787589-7a55b475-8d71-4fb2-8bb2-6d68a4e617d1.png)

If there is already a way to do this, that I didn't found in the documentation, please let me know.

Thanks in advance!
