### ISSUE TITLE
Camera Preview not loading 

### ISSUE THREAD

**Issue by neerazz** [fuatakgun/eufy_security#504]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
I have followed the instructions as per: https://github.com/fuatakgun/eufy_security#6-installation.
My home assistant is installed in docker, I see all the entities and the status of it.

But when I try to preview I run into blank screen. I don't have RTSP enabled, I wanted it to be on P2P configuration.

Any help related would be greatly applicated.

Also I keep getting the below notification in my HA:

> Eufy Security - Not Enabled - RTSP
> RSTP needs to enabled for Camera Garage

Docker compose file:
```
  homeassistant:
    hostname: homeassistant
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './homeassistant:/config'
      - './homeassistant/media:/media'
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  eufy-security:
    image: bropat/eufy-security-ws:latest
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: eufy-security
    volumes:
      - ./eufy-security/data:/data
    ports:
      - '3000:3000'
    environment:
      - USERNAME=
      - PASSWORD=
      - COUNTRY=US
    restart: unless-stopped

  p2p-streaming:
    image: aler9/rtsp-simple-server:latest
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: p2p-streaming
    volumes:
      - ./eufy-security/data:/data
    ports:
      - '8554:8554'
      - '1935:1935'
    environment:
      - RTSP_PROTOCOLS=tcp
    restart: unless-stopped
```

**To Reproduce**
1. Go to ``` Run the docker compose file.``` 
2. Click on ``` Once both the container starts, add a HACS. Then Go to settings and integrations.``` 
> Once both the container starts.
> Add the Eufy to HACS.
> Go to settings and integrations, add the Eufy Security Integration.
> Configurations properties are as below:
>> Cloud Scan interval in seconds: 600
>> Use RTSP Add On (P2P): (Tried with both enabled and disabled) ran into same error.
>> Video Analysis Duration in Seconds: 2
>> Auto start Stream on Click: (Tried with both enabled and disabled) ran into same error.
> When I click on the camera entity, I see a blank page.
> In logs I see error, "Timeout getting stream source"

**Expected behavior**
The expectation is to load the camera preview.

**Screenshots**

**Hardware Information about Home Assistant: Pi-4, HA on Docker

**Hardware Information about Cameras
- Camera Model: eufyCam 2 Wireless
- Live Streaming Protocol: P2P

**Additional context**
