### ISSUE TITLE
PTZ services are not working

### ISSUE THREAD

**Issue by satyambaba** [fuatakgun/eufy_security#512]
I have three Eufy 2K indoor pan and tilt cameras, all PTZ commands work flawlessly on two of them, let's call them A & B, however none of the PTZ commands work on one of them, let's call it C. All three cameras have the same firmware version 2.1.2.4.

Both methods (eufy_security.send_message and eufy_security.ptz_left) work for A & B, however none of them works for C.

Method 1 :

```yaml
service: eufy_security.send_message
data:
  message: |-
    {
      "messageId": "cmdPanAndTiltUp",
      "command": "device.pan_and_tilt",
      "serialNumber": "T8410PXXXXXXXXXX",
      "direction": 1
    }
```

Method 2 :

```yaml
service: eufy_security.ptz_left
data:
  entity_id: camera.kitchen_camera
```

Please note that, for camera C both these methods show success message in the logs, however it doesn't work in reality. Also, PTZ works perfect for the same camera (C) when I use the Eufy app. I also verified multiple times that I am entering the correct serial number for C.

I am not sure what is causing this behavior for camera C, every setting in the Eufy app is same across A, B and C. Please help me, thanks in advance.
