### ISSUE TITLE
No picture when doorbell camera is not streaming

### ISSUE THREAD

**Issue by skrobul** [fuatakgun/eufy_security#604]
**Describe the bug**

**To Reproduce**
1. Start P2P stream from the doorbell
2. Stop the P2P stream using `eufy.stop_p2p_livestream` or `camera.turn_off` service
3. See that `entity_picture` state attribute points to ` /api/camera_proxy/camera.doorbell?token=....` that returns 500 Internal server error. Currently, if retrieving the image from eufy fails with non-200, [there is no additional logging](https://github.com/fuatakgun/eufy_security/blob/fd91216dbf12df4251b04e6dde62887fb33b2d09/custom_components/eufy_security/camera.py#L443) as far as I understand.

**Expected behavior**
Valid picture retrieved and cached.

**Screenshots**
![image](https://user-images.githubusercontent.com/183976/209863272-5de99c8c-ae8e-4ad0-a511-b710594bbd76.png)

**Hardware Information about Home Assistant

**Hardware Information about Cameras
- Camera Model: T8222-Z
- Live Streaming Protocol: P2p

**Additional context**

It has stopped working recently. I suspected that it may be as a result of the [recent privacy scandal](https://www.theverge.com/2022/11/30/23486753/anker-eufy-security-camera-cloud-private-encryption-authentication-storage) where Eufy was caught uploading the footage and pictures to the cloud.

Those suspicions were confirmed when I checked the raw properties through `eufy-security-ws` client:
```json
{
  "type": "result",
  "success": true,
  "messageId": "get_properties",
  "result": {
    "serialNumber": "T822CAMERA_SERIAL",
    "properties": {
      "name": "Doorbell",
      "model": "T8222-Z",
      "serialNumber": "T822CAMERA_SERIAL",
      "stationSerialNumber": "T8020REDACTED_STATION_SERIAL",
      "pictureUrl": "T8020REDACTED_STATION_SERIAL~/media/mmcblk0p1/video/20221228183018_c00.jpg"
      // truncated for visibility
    }
 }
}

```

**Full output**
<details>
```

eufy-security> device.get_properties T822CAMERA_SERIAL
eufy-security> {
  type: 'result',
  success: true,
  messageId: 'get_properties',
  result: {
    serialNumber: 'T822CAMERA_SERIAL',
    properties: {
      motionDetected: false,
      personDetected: false,
      personName: '',
      ringing: false,
      name: 'Doorbell',
      model: 'T8222-Z',
      serialNumber: 'T822CAMERA_SERIAL',
      type: 16,
      hardwareVersion: 'T8222-Z',
      softwareVersion: '3.6.4',
      stationSerialNumber: 'T8020REDACTED_STATION_SERIAL',
      lastChargingDays: 44,
      lastChargingFalseEvents: 114,
      lastChargingRecordedEvents: 641,
      lastChargingTotalEvents: 755,
      batteryUsageLastWeek: 0,
      pictureUrl: 'T8020REDACTED_STATION_SERIAL~/media/mmcblk0p1/video/20221228183018_c00.jpg',
      recordingClipLength: 100,
      recordingRetriggerInterval: 2,
      recordingEndClipMotionStops: true,
      snoozeTime: 0,
      snoozeHomebase: false,
      snoozeStartChime: false,
      snoozeMotion: false,
      snoozeStartTime: 0,
      state: 1,
      chimeHomebase: true,
      notificationType: 2,
      notificationRing: true,
      notificationMotion: true,
      enabled: true,
      battery: 54,
      batteryTemperature: 9,
      watermark: 1,
      motionDetection: true,
      motionDetectionSensitivity: 4,
      chimeHomebaseRingtoneType: 0,
      videoStreamingQuality: 0,
      chimeHomebaseRingtoneVolume: 16,
      autoNightvision: true,
      videoWdr: false,
      chargingStatus: 2,
      snooze: false,
      statusLed: true,
      chimeIndoor: false,
      audioRecording: true,
      speakerVolume: 100,
      ringtoneVolume: 80,
      wifiRssi: -59,
      wifiSignalLevel: 4,
      motionDetectionType: 2,
      powerWorkingMode: 2
    }
  }
}
```
</details>

This indicates that the image should be retrieved directly from the station rather than AWS which is great news from privacy and reliability standpoint, but it's no longer a valid URL so the HTTP get obviously fails. I have not figured out how to construct the correct URL. Will try when I have more time, but I am open to suggestions :)

**Comment by fuatakgun** [comment]
if you are using alpha version of integration, it would cache the live stream picture and hold it until next restart.

**Comment by skrobul** [comment]
Amazing, thank you very much for  prompt response - I will switch to the alpha version and monitor the linked issue

**Comment by skrobul** [comment]
> if you are using alpha version of integration, it would cache the live stream picture and hold it until next restart. 

@fuatakgun are there any specific steps needed to enable this functionality? I have pulled the `alpha`, specifically the 21032814c82e37e9f39de31841311958e90a8eec and it does not seem to be cached...  [Debug log](https://gist.githubusercontent.com/skrobul/cc63f30801ea308b2644006aa2b417a0/raw/adab29b150fa522be06f7e71d7c643d59acb7f08/gistfile1.txt). Any clues?

**Comment by fuatakgun** [comment]
any way, you can try with v5.2.2?

**Comment by skrobul** [comment]
> any way, you can try with v5.2.2?

checked out the `v5.2.2` (475bcb0), restarted the home assistant, ended up with the same result (no picture).

[Debug logs](https://gist.github.com/skrobul/39c4bfb70583fbe0d37d6d503e912028)

I am using following script to start and stop stream:

<details>

```yaml
alias: camera on off
sequence:
  - service: camera.turn_on
    data: {}
    target:
      device_id: 51dae52de6ceb592048e0352ca7dcfdb
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: camera.turn_off
    data: {}
    target:
      device_id: 51dae52de6ceb592048e0352ca7dcfdb
mode: single
```

</details>

The video starts and stops as expected.

**Comment by fuatakgun** [comment]
Can you share your front end YAML card setup? Do you have picture card to render camera image?

**Comment by fuatakgun** [comment]
Ok, i see, you want to take care of this via automation not on rendering. I need to this about it.

**Comment by skrobul** [comment]
> Can you share your front end YAML card setup? Do you have picture card to render camera image?

Sure, here it is:

```yaml
type: vertical-stack
cards:
  - type: conditional
    conditions:
      - entity: camera.doorbell
        state: idle
    card:
      type: picture-entity
      entity: camera.doorbell
      tap_action:
        action: call-service
        service: camera.turn_on
        service_data: {}
        target:
          entity_id: camera.doorbell
  - type: conditional
    conditions:
      - entity: camera.doorbell
        state: streaming
    card:
      type: custom:webrtc-camera
      ui: true
      url: rtsp://192.168.1.200:8554/T8222SERIAL
      shortcuts:
        top: 10
        left: 0
        orientation: horizontal
        services:
          - name: Stop
            icon: mdi:record-circle-outline
            service: camera.turn_off
            service_data:
              entity_id: camera.doorbell
```
