### ISSUE TITLE
Unable to select guard mode in automation on home assistant

### ISSUE THREAD

**Issue by multinet33** [fuatakgun/eufy_security#605]
With the latest version if the add on 5.1.7 a previous working automation for selecting the guard mode (in home assistant / automation : call a service : eufy_security.alarm_arm_custom1) does not work anymore (service not found)

How to select guard mode in automation ?

thank you

**Comment by fuatakgun** [comment]
you have now guard_mode entity, you can use it.

but i have implemented these services, please get v5.2.2

**Comment by multinet33** [comment]
Ok

how to use guard mode entity in the actio. Section of an automation (home assistant) ? I’m unable to find the way

thank you

**Comment by fuatakgun** [comment]
These are options: Away, Home, Schedule, Custom 1, Custom 2, Custom 3, Geofencing, Disarmed

```
service: select.select_option
data:
  option: Home
target:
  entity_id: select.home_base_guard_mode
```
