### ISSUE TITLE
Discrepancy between cameras/display

### ISSUE THREAD

**Issue by chicknlil** [fuatakgun/eufy_security#608]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**

Not sure this is necessarily a bug, but with the camera cards working on my dash now (yay!!) I've noticed that on two largely identical views, the two cameras I have (doorbell, backyard) display completely different, despite adjusting the settings to be identical.  See screenshots below.

**To Reproduce**

See bug info.

**Expected behavior**

Images to be a close if not identical size, and information displayed to be otherwise identical (date format and clarity are QUITE different). Ideally both should look/display like the backyard camera.

**Screenshots**

![image](https://user-images.githubusercontent.com/100124187/210050606-1fb08eea-5c1e-4bfc-8a6b-7552fbf48932.png) 
![image](https://user-images.githubusercontent.com/100124187/210050656-7703566b-16b1-4171-9809-0796a0142d04.png)

**Hardware Information about Home Assistant
Odroid-N2

**Hardware Information about Cameras
- Camera Model
T8422 (Backyard) and T8200 (Doorbell)
- Live Streaming Protocol: RTSP or P2p
P2P

**Additional context**

Am on the Alphas (5.2.6, which is the latest as the time I type this).

**Comment by fuatakgun** [comment]
I think i still have your cameras shared, can i take a look at it this weekend?

**Comment by chicknlil** [comment]
Absolutely!  If you end up playing with the lock again, the cats will be thoroughly entertained.

**Comment by fuatakgun** [comment]
Devices stream in different formats, so captured images are shown in different dimensions. Pasting two screenshots from eufy mobile app directly. I would say, take a look at card based solutions (i am not aware any) to set the height of cards in UI.

Doorbell
![Screenshot_2022-12-30-10-36-41-049-edit_com.oceanwing.battery.cam.jpg](https://user-images.githubusercontent.com/11085566/210055937-1e7aa358-b6fd-4fa7-a3b8-b4accb82206b.jpg)

Backyard
![Screenshot_2022-12-30-10-37-02-274-edit_com.oceanwing.battery.cam.jpg](https://user-images.githubusercontent.com/11085566/210055947-08771709-838d-4ac9-8046-38cc226cf9b5.jpg)

**Comment by fuatakgun** [comment]
Please let me know if you want to delete the screenshots.

**Comment by chicknlil** [comment]
Nah, the images are fine, they don't reveal anything, especially at night!

I wonder why it does the date like that, differently? Or the size differently? I think I might be able to use a layout card to adjust the height max. Will try and circle back.

**Comment by fuatakgun** [comment]
I have 4 units of 2c cameras but they have different model numbers and so different firmware.
Timestamp font is also different for these cameras.

**Comment by chicknlil** [comment]
Hrm. Tried using the [lovelace layout card](https://github.com/thomasloven/lovelace-layout-card) (grid view - so replacing the grid view you had used) and setting the height to 350 px (which appears to be the height of the backyard camera). Didn't seem to make a difference.

Here's the slightly revised code.

```
  - type: custom:layout-card
    layout_type: custom:grid-layout
    layout: 
      - height: 350 px
    cards:       
      - type: conditional
        conditions:
          - entity: camera.doorbell
            state: idle
        card:
          show_state: true
          show_name: true
          type: picture-entity
          entity: camera.doorbell
          camera_image: camera.doorbell
          tap_action:
            action: call-service
            service: camera.turn_on
            data: {}
            target:
              entity_id: camera.doorbell
      - type: conditional
        conditions:
          - entity: camera.doorbell
            state: streaming
        card:
          type: vertical-stack
          cards:
            - show_name: true
              show_icon: false
              type: button
              tap_action:
                action: call-service
                service: camera.turn_off
                data: {}
                target:
                  entity_id: camera.doorbell
              entity: camera.doorbell
              name: Stop
            - type: custom:webrtc-camera
              entity: camera.doorbell
```

Maybe someone else will see this and get some use out of it or have a suggestion to how to tweak it better.
