### ISSUE TITLE
Home Assistant - Switch cam on off

### ISSUE THREAD

**Issue by SmartM-ui** [fuatakgun/eufy_security#61]
Hi @fuatakgun 
would it be possible to integrate the switch to turn the cam on and off? 
In the original app, the switch, is called "Camera on" useful for privacy when you are at home.
I would like to use the switch to activate the automations in the home assistant.
Thanks

**Comment by fuatakgun** [comment]
Hey, enable and disable services should be enough for you.

**Comment by SmartM-ui** [comment]
> Hey, enable and disable services should be enough for you.

Hi @fuatakgun 
Thanks for the advice,
i tried and the service works. It manages to turn the cam on and off.
I created a switch, place the code if it can be of help to anyone:

```
switch:
  - platform: template
    switches:
      eufy_on_off:
        turn_on:
          service: eufy_security.enable
          data: {}
          target:
            entity_id: camera.xxx
        turn_off:
          service: eufy_security.disable
          data: {}
          target:
            entity_id: camera.xxx
```
I have another request regarding the on / off status of the cam.

Is a sensor or attribute already available to understand if the cam is actually on or off?

Thanks
