### ISSUE TITLE
Automation based on person detection event not triggering

### ISSUE THREAD

**Issue by chicknlil** [fuatakgun/eufy_security#616]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**

I have an automation that fired with previous versions of the automation (pre 5.0) but no longer does so with the alpha releases.  I have tried `binary_sensor.doorbell_motion_detected` but it did not trigger; neither did `binary_sensor.doorbell_person_detected` . I believe this was previously called by `binary_sensor.doorbell_global_motion_detected` or something like that.

**To Reproduce**

n/a

**Expected behavior**

The automation to fire and let me know someone has approached my front door.

**Screenshots**

![image](https://user-images.githubusercontent.com/100124187/210139209-587e3c9a-9fe9-40c6-ae75-c9603231b36a.png)

**Hardware Information about Home Assistant
Odroid-N2

**Hardware Information about Cameras
- Camera Model
T8200
- Live Streaming Protocol: RTSP or P2p
P2p

**Additional context**

Here's the current version of the automation:

```
alias: Person Alert
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.doorbell_person_detected
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 1
condition:
  - condition: time
    before: "22:00:00"
    after: "06:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
action:
  - service: script.turn_on
    target:
      entity_id: script.google_home_resume
    data:
      variables:
        action:
          - service: tts.google_cloud_say
            data:
              entity_id: media_player.speakers
              message: <speak> <break time="2s"/>There's someone at the door.</speak>
            cache: true
mode: single

```
