### ISSUE TITLE
Unable to find service eufy_security.generate_image

### ISSUE THREAD

**Issue by akilham** [fuatakgun/eufy_security#660]
**Describe the bug**

I am trying to have Home Assistant send a notification to my phone (Android) when the doorbell detects motion. I'm using the following automation which is mostly just copy/pasted from the README:

```
alias: Doorbell motion detected
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.doorbell_person_detector_sensor
    to: "on"
action:
  - service: eufy_security.start_p2p_livestream
    data: {}
    target:
      entity_id: camera.doorbell
  - service: eufy_security.stop_p2p_livestream
    data: {}
    target:
      entity_id: camera.doorbell
  - service: notify.mobile_app_pixel_6_pro
    data:
      message: Motion detected
      data:
        image: /api/camera_proxy/camera.doorbell
        actions:
          - action: ALARM
            title: Alarm
          - action: SNOOZE
            title: Snooze
mode: single
```

It is not completing, and when I view the `Trace Timeline` for the automation run it shows this error:

```
Triggered by the state of binary_sensor.doorbell_person_detector_sensor at 6 January 2023 at 17:14:10
Call service eufy_security.start_p2p_livestream on entities camera.doorbell
Call service eufy_security.generate_image on entities camera.doorbell
(camera.doorbell) turned Streaming - p2p
Stopped because an error was encountered at 6 January 2023 at 17:14:10 (runtime: 0.01 seconds)

Unable to find service eufy_security.generate_image
```

I also cannot see the service `eufy_security.generate_image` in developer tools.

**Additional information**

Eufy Addon version: 1.3.0
RTSP Simple Server Add-on: 0.17.6

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type: OS
- Home Assistant Core Version: core-2022.8.7

Hardware Information;
- Camera Model: Eufy 2K doorbell camera T8210

- Live Streaming Protocol (RTSP/P2P): I have the RTSP protocol set up and working

- Would you share your device with me in case further debugging required? Yes
