### ISSUE TITLE
eufy_security.enable - eufy_security.disable doesn't work

### ISSUE THREAD

**Issue by SmartM-ui** [fuatakgun/eufy_security#696]
Hi,
I used the enable and disable service to turn the webcam on and off by double clicking and holding action in Home Assistant button. The service appears to be no longer active.
How can I fix?

Thank you in advance

```
hold_action:
   action: call-service
   service: eufy_security.disable
   service_data:
     entity_id: camera.firstfloor

double_tap_action:
   action: call-service
   service: eufy_security.enable
   service_data:
     entity_id: camera.secondfloor
type: custom:button-card
```
