### ISSUE TITLE
RTSP Simple Server Add-on: "Port '8554' is already in use by something else on the host

### ISSUE THREAD

**Issue by Raarrrinator** [fuatakgun/eufy_security#716]
Hi there,

I've just noticed that the RTSP Simple Server Add-on can't start because of a port conflict.

When starting it reports: "Port '8554' is already in use by something else on the host."

I've tried changing the port to 8555 in the Eufy Security integration and trying to connect to the new port, but with the same result.

I've checked the other integrations and add-ons but non seem to use port 8554 besides the Eufy Security integration.

Thanks in advance for the assistance!

![rtsp](https://user-images.githubusercontent.com/69963716/215742579-c3f56d49-20c4-4e7a-84d1-0d2724a67f96.JPG)

Info:
RTSP Simple Server Add-on - version v0.17.6
Eufy Security integration - latest 
Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230110.0 - latest

**Comment by Sierek** [comment]
Check if you don't have this port set up in WebRTC Camera.

**Comment by Raarrrinator** [comment]
Removing WebRTC did the trick!

But Fuatakgun does advice to use it next to RTSP Simple Server...

**Comment by fuatakgun** [comment]
Change rtsp addon server to something else, restart it and then configure integration according to your custom port. These are standard home assistant staff, nothing custom here.

**Comment by xBodziu** [comment]
> 1- Change rtsp addon server port to something else 2- restart it 3- configure integration according to your custom port.
> 
> These are standard home assistant staff, nothing custom here.

Hello, I am new at HA.

Could you please tell me how to change RTSP addon server port?? There is nothing at configuration tab. 

Thanks!!!

**Comment by fuatakgun** [comment]
Please ask help over home assistant community forum, there is a specific thread for the integration.

**Comment by MihaiP17** [comment]
If it helps, the following steps fixed this issue for me:
 1. Disable WebRTC integration.
 2. Start RTSP Simple Server add-on. This time did not gave me the port conflict message.
 3. Enable WebRTC integration.
Now everything works again as expected.

**Comment by shortie292914** [comment]
Every time I restart HA fully. I lose RTSP due to the webRTC camera taking control of port 8554. Any suggestions so that I can restart HA with no issues on boot for RTSP?

**Comment by gielk** [comment]
I automated the process of disabling WebRTC, then starting the RTSP add-on, and finally enabling WebRTC. I have installed Spook, an integration that allows for the disabling or enabling of integrations and provides many other handy tools.

Check out Spook at: https://github.com/frenck/spook

Here is my automation.
```
alias: Fix RTSP en WebRTC port deurbel
description: ""
trigger:
  - platform: homeassistant
    event: start
action:
  - action: homeassistant.disable_config_entry
    metadata: {}
    data:
      config_entry_id: 2553166f750713993523e6988de7d762
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - action: hassio.addon_start
    metadata: {}
    data:
      addon: 75a80a57_rtsp_simple_server
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - action: homeassistant.enable_config_entry
    metadata: {}
    data:
      config_entry_id: 2553166f750713993523e6988de7d762
```
