### ISSUE TITLE
Eufy 2k Doorbell

### ISSUE THREAD

**Issue by Mari143** [fuatakgun/eufy_security#764]
I have followed the instructions step by step but the sensors of the doorbell aren't working. 

The motion detection/person detection always states "clear" even when there is motion.
The doorbell thumbnail is constantly black/empty and the the streaming also does not work even when I press "start p2p streaming"

The configuration and diagnostic section are working more or less e.g. battery status etc.
So I'm not sure whether the wireless 2k doorbell isnt supported or I've done something wrong while setting up.

Any ideas how I can resolve this?
Thanks!

**Comment by Ascathon** [comment]
Do you (also) have motion detection set in the Eufy app? The camera/homebase only pushes motion information to the API when it is enabled for the app itself too (shame).

**Comment by nihadmehmedovic** [comment]
Have the same issues with the 2k doorbell. The streaming just doesn't work properly. It manages to create a thumbnail after pressing `start p2p streaming` but thats all, no video stream. Both the `RTSP Simple Server` and `WebRTC ` are installed.

**Comment by wouterDevelop** [comment]
same issue as @nihadmehmedovic, in VLC I get 1 frame of video. and when I restart te stream  I get a new frame.

**Comment by Mari143** [comment]
> Do you (also) have motion detection set in the Eufy app? The camera/homebase only pushes motion information to the API when it is enabled for the app itself too (shame).

Yes Its enabled. I wonder if the 2k doorbell works for anyone else with this integration. I dont even have the sensors working such as motion detection. Its always clear! Let alone the video stream.

**Comment by polo1469** [comment]
Hi
I'm also have a problem with the Eufy doorbell 😥
I have tried to follow the installation steps, and it looks like most is working, but I can't get the videostream to work 😥
I just have a gray picture. I can start "Start P2P Stream", and I can see on the doorbell that it gets the signal (the ring turns blue), but I can't get the image (the camera sensor do change from inactive to streaming). 
Any ideas on how to get the video stream to work?

**Comment by Egregius** [comment]
I also installed an Eufy 2K doorbell last week and especially Home Assistant to have it connected to my Domoticz installation. 
I created an automation on the doorbell, that works perfectly. 
`alias: When Deurbel Ringing changes to on
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.doorbell_ringing
    to: "on"
condition: []
action:
  - service: shell_command.domoticz_doorbell
    data: {}
mode: single
`
But not for motion. 
`alias: " When Deurbel Person detected changes to on"
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.doorbell_person_detected
    to: "on"
condition: []
action:
  - service: shell_command.domoticz_motion
    data: {}
mode: single
`

Also the camera card stays black, but that's not that important to me. I just like to turn on the light when motion is detected.

**Comment by ginfts** [comment]
The Battery Percentage on my two Doorbell cameras is not being updated within HA; I charged them both yesterday to 100% - and that is what is reported within the Eufy iOS app - but even after 36 hours they are showing 34% and 6%.

**Comment by Egregius** [comment]
I noticed that to. I do think that it'll be updated if you reboot HA. At least for the battery temperature that's the case.

**Comment by ginfts** [comment]
Thanks for that. But just for the record, re-starting HA didn't solve my battery reporting issue.

**Comment by sm00tje** [comment]
having the same issues. i did notice the doorbell stream is working on the home assistant android app but not on pc (webbrowser) for some reason. so i did some reading and it seems the doorbell streams H265 which isn't supported in most webbrowsers(can't confirm yet).

**Comment by jimmi1982** [comment]
Im experiencing the same problems, all the sensors work fine but cannot get an image.

**Comment by kvanbiesen** [comment]
LikeWise, (some from floodlight 2 btw)....

**Comment by kdill00** [comment]
reducing the cameras resolution worked for me and forcing the stream quality to a set one instead of auto helped smooth it more.  Same for the floodlight camera someone mention. Also the start stream p2p I found doesn’t work for me unless I call the button press service to “press” it.

**Comment by tomweda** [comment]
i have the same issue... i have the T8220 wireless doorbel. all features looks to work but cant get the P2P stream to work.

**Comment by MrBretticus** [comment]
> reducing the cameras resolution worked for me and forcing the stream quality to a set one instead of auto helped smooth it more. Same for the floodlight camera someone mention. Also the start stream p2p I found doesn’t work for me unless I call the button press service to “press” it.

Can confirm this worked for me too. Thank you for the tip.

**Comment by exCat01** [comment]
> reducing the cameras resolution worked for me and forcing the stream quality to a set one instead of auto helped smooth it more. Same for the floodlight camera someone mention. Also the start stream p2p I found doesn’t work for me unless I call the button press service to “press” it.

How did you do this? Could you show me the code?

**Comment by exCat01** [comment]
How can I retrieve the last recorded camera image? That might be enough for me if the stream doesn't work.

**Comment by MrBretticus** [comment]
> How can I retrieve the last recorded camera image? That might be enough for me if the stream doesn't work.

Here is an example dashboard card that is working for me with P2P streaming. A few notes about this setup:

- requires WebRTC addon
- requires RTSP Simple Server Add-on
- the `<streamURL>` is specific to your config and can be copied from the device info page
- the extra query parameters the I configured on the stream URL are to force a specific video and audio format for compatibility, you may not need this
- I needed to reduce the camera resolution for this to work via P2P
- the extra entities are just for me to keep an eye on the device status, not required
- the camera image only shows up after activating the stream at least once, it also goes if you restart HA

FYI, I was able to also get RTSP streaming working for my two Cameras, but not for the doorbell. As a result I just set them all to P2P instead.

```yaml
type: vertical-stack
cards:
  - type: conditional
    conditions:
      - entity: sensor.doorbell_stream_status
        state: StreamStatus.IDLE
    card:
      show_state: true
      show_name: true
      camera_view: auto
      type: picture-entity
      entity: camera.doorbell
      camera_image: sensor.doorbell_last_camera_picture_url
      tap_action:
        action: call-service
        service: eufy_security.start_p2p_livestream
        target:
          entity_id: camera.doorbell
        data: {}
      image: camera.doorbell
  - type: conditional
    conditions:
      - entity: sensor.doorbell_stream_status
        state_not: StreamStatus.IDLE
    card:
      type: vertical-stack
      cards:
        - type: custom:webrtc-camera
          url: >-
            <streamUrl>?video=h264&audio=aac&audio=opus
        - show_name: true
          show_icon: false
          type: button
          entity: button.doorbell_stop_p2p_stream
          name: Stop
          show_state: false
          tap_action:
            action: toggle
          hold_action:
            action: toggle
  - type: entities
    entities:
      - entity: sensor.doorbell_battery_percentage
        name: Battery
      - entity: sensor.doorbell_stream_status
        name: Status
      - entity: sensor.doorbell_wifi_signal_level
        secondary_info: none
        name: WiFi
    state_color: true
```
