### ISSUE TITLE
HomeBase Current Mode on startup

### ISSUE THREAD

**Issue by caseybrown-dev** [fuatakgun/eufy_security#773]
When the integration is first started or restarted, Current Mode is reported as Unknown. However, Guard Mode is correctly reporting the alarm state.

It would be nice if Current Mode could be derived from Guard Mode on startup, unless there are other cases I'm not aware of.

I am using a HomeBase 3 with all push notifications properly configured.

**Comment by googanhiem** [comment]
Current fix I'm using, add this to your configuration.yaml

```
alarm_control_panel:
  - platform: template
    panels:
      homebase_3:
        value_template: >-
          {% set ARM = states.select.homebase_guard_mode.state %}
          {%- if ARM == "Home" -%}
          armed_home
          {%- elif ARM == "Away" -%}
          armed_away
          {%- elif ARM == "Disarmed" -%}
          disarmed
          {%- else %}
          unknown
          {%- endif %}        
        arm_away:
          service: select.select_option
          data:
            option: Away
          target:
            entity_id: select.homebase_guard_mode
        arm_home:
          service: select.select_option
          data:
            option: Home
          target:
            entity_id: select.homebase_guard_mode
        disarm:
          service: select.select_option
          data:
            option: Disarmed
          target:
            entity_id: select.homebase_guard_mode
        code_arm_required: false
```
