### ISSUE TITLE
Floodlight T8424 P2P not working.

### ISSUE THREAD

**Issue by kvanbiesen** [fuatakgun/eufy_security#788]
**Describe the bug**

T8424 Floodlight, should be supported fully according to bropat. The device get listed and the sensors become visible. Only the streaming doesnt work.

The camera doest have a service camera.turn_on or something, it does have a diagnostic button.back_door_start_p2p_stream. It seems to enable tot rtsp stream in the settings (gives a local url) but nothing is able to connect to it. Also the little thumnail in front of the camera stays black and status stays idle. 

**To reproduce**
```python
- type: conditional
    conditions:
      - entity: camera.back_door
        state: idle
    card:
      show_state: true
      show_name: true
      camera_view: auto
      type: picture-entity
      entity: camera.back_door
      camera_image: camera.back_door
      tap_action:
        service: button.press
        service_data: {}
        target:
          entity_id: button.back_door_start_p2p_stream
  - type: conditional
    conditions:
      - entity: camera.back_door
        state: streaming
    card:
      type: vertical-stack
      cards:
        - show_name: true
          show_icon: false
          type: button
          tap_action:
            service: button.press
            service_data: {}
            target:
              entity_id: button.back_door_start_p2p_stream
            entity: camera.back_door
          name: Stop
        - type: custom:webrtc-camera
          entity: camera.back_door
``` 
  
`

Doesnt throw an error, but the state from the camera stays idle and because of that, the video doesnt show up most likely
Also the tiny thumb in front of the camera stays black. Think because of the state doesnt get updates/read correctly, it doesnt work.

All other switches seem to work, besides enable motion detection, that throws an error also :/

**Expected behavior**
P2P stream like with all other eufy devices

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
, Eufy Security Add-on (1.3.0), RTSP Simple Server Add-on (v0.17.6)
running core 2023.4.6

- Would you share your device with me in case further debugging required? (Yes/No): 

Yes, Gladly :)

**Comment by kdill00** [comment]
I had to setup the 8423 flood light which is pretty much the same thing. It does not work as well as other eufy devices with this home assistant addon. The best I could get it to work was using a script and having it call p2p turn on and camera.turn_on using run in parallel. This camera fails to be responsive it seems and it doesn’t load.  This is my card:

```

          - type: conditional
            conditions:
                - entity: camera.driveway
                  state: streaming
            card:
              type: vertical-stack
              cards:
                - type: picture-entity
                  entity: camera.driveway
                  show_state: false
                  show_name: false
                  camera_image: camera.driveway
                  tap_action:
                    action: call-service
                    haptic: sucesss
                    service: script.drivewayon

          - type: conditional
            conditions:
                - entity: camera.driveway
                  state: streaming
            card:
                type: vertical-stack
                cards:
                   - show_name: true
                     show_icon: false
                     type: button
                     tap_action:
                       action: call-service
                       service: script.drivewayoff
                     entity: camera.driveway
                     name: Stop
                  - type: custom:webrtc-camera
                    entity: camera.driveway

```
```
alias: drivewayon
sequence:
    - parallel:
      - service: camera.turn_on
        data: {}
        target:
          entity_id: camera.driveway
      - service: button.press
        data: {}
        target:
          entity_id: button.driveway_start_p2p_stream
  - wait_for_trigger:
      - platform: state
        entity_id:
          - camera.driveway
        to: streaming
        for:
          hours: 0
          minutes: 0
          seconds: 2
    timeout:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: eufy_security.generate_image
    data: {}
    target:
      entity_id: camera.driveway
mode: single       
```

this was the only way I could get it to work. I tried automations, cards with tap actions ect.  I am assuming you have everything else setup correctly. It needs to be a script for some reason and calling both of those commands seems to be my bootleg fix. You can reduce delay times if your home assistant is running on a faster machine. This was a raspberry pi 4 so it needs a few seconds to load between commands or something. Hopefully it can be corrected in the future.

**Comment by kdill00** [comment]
If the addon perceives the device is already streaming any turn on command or start command will fall flat and stop any script or automation. You will still probably get an error from the script when starting. So far this has “worked” for now. It’s still just a bootleg solution if it even is a solution

**Comment by kvanbiesen** [comment]
> If the addon perceives the device is already streaming any turn on command or start command will fall flat and stop any script or automation. You will still probably get an error from the script when starting. So far this has “worked” for now. It’s still just a bootleg solution if it even is a solution

Nope,

tried applying this to my setting, nothing working. Well it comes now exetly at the time where the prictureUrl is gone update from bropat. Dunno if this repo needs updating for that...

**Comment by fuatakgun** [comment]
share the camera with me following README file

**Comment by codyc1515** [comment]
Hi. I'm not in either region so wasn't sure which account to share to, so I shared with both. Trust it helps :)

**Comment by codyc1515** [comment]
Thank you for checking. We're there issues with the higher options? I seemed to be getting out of memory crashes in Docker recently from ffmpeg and wondered if this may be related (haven't confirmed yet).

**Comment by kvanbiesen** [comment]
got mine working. Its a little slow to start but it works:

here is the code, maybe its usefull for someone

```
  - type: conditional
    conditions:
      - entity: camera.back_door
        state: idle
    card:
      show_state: true
      show_name: true
      type: picture-entity
      entity: camera.back_door
      camera_image: camera.back_door
      tap_action:
        action: call-service
        service: camera.turn_on
        data: {}
        target:
          entity_id: camera.back_door
  - type: conditional
    conditions:
      - entity: sensor.back_door_stream_status
        state: StreamStatus.STREAMING
    card:
      type: vertical-stack
      cards:
        - show_name: true
          show_icon: false
          type: button
          tap_action:
            action: call-service
            service: button.press
            data: {}
            target:
              entity_id: button.back_door_stop_p2p_stream
          entity: camera.back_door
          name: Stop
        - type: custom:webrtc-camera
          entity: camera.back_door
```


maybe it works with the camera_turn_off also and stuff but havent checked that, like this its working
