### ISSUE TITLE
How to setup pin code for provided alarm_control_panel?

### ISSUE THREAD

**Issue by fliespl** [fuatakgun/eufy_security#792]
Searching the web / issues didn't help me...

**Comment by fliespl** [comment]
Found it immediately after posting (and search 30 minutes before).

configuration.yaml
```
homeassistant:
  customize:
    alarm_control_panel.dom:
      code_format: number
      code_arm_required: false
      code_disarm_required: true
      code: 0000
```
