### ISSUE TITLE
EufyCam 2 Pro and T8210 video doorbell stuck on 'idle'

### ISSUE THREAD

**Issue by JimboJamez** [fuatakgun/eufy_security#805]
**Describe the bug**

I have two EufyCam 2 Pro and one T8210 video doorbell integrated into Home Assistant through the Eufy Security integration. I can see the devices in HA, and have a miriad of enities available as well, the example below is from the T8210:

![Untitled](https://github.com/fuatakgun/eufy_security/assets/25968238/5aebf525-a9f1-4800-93be-12c17f041e9b)

The issue I am having is that while other sensors like 'Motion Detected' and 'Ringing' will update when triggered, the camera streams are stuck on 'idle'

![image](https://github.com/fuatakgun/eufy_security/assets/25968238/c63d4a7d-57cc-4b31-9856-a683b35b7892)

I beleive that I have configured the yaml correctly (example below) and would like to know if this is a bug, or if it is something I am missing?

```
square: false
type: grid
columns: 1
cards:
  - type: entities
    entities:
      - entity: binary_sensor.garage_doorbell_motion_detected
        name: Motion detected
      - entity: binary_sensor.garage_doorbell_person_detected
        name: Person detected
      - entity: binary_sensor.garage_doorbell_ringing
        name: Ringing
      - entity: sensor.garage_doorbell_battery_percentage
      - entity: sensor.garage_doorbell_battery_temperature
      - entity: switch.garage_doorbell_camera_enabled
      - entity: number.garage_doorbell_speaker_volume
      - entity: sensor.garage_doorbell_wifi_signal_level
        name: Stream Status
    title: Garage Doorbell
  - show_state: true
    show_name: true
    camera_view: auto
    type: picture-entity
    entity: camera.garage_doorbell
    camera_image: camera.garage
    name: Rear Door
```
