### ISSUE TITLE
Troubles with Eufy 2k Wired

### ISSUE THREAD

**Issue by TonyHeadband** [fuatakgun/eufy_security#841]
Hello there,
I'm trying to stream the Eufy 2k Wired but I only got errors, I have another eufy camera the S220 and it works fine.
I tried multiple setup without success.

```
type: custom:webrtc-camera
entity: camera.doorbell
```

![image](https://github.com/fuatakgun/eufy_security/assets/41022017/05d1c7e6-8bf7-4e29-a61e-e1c82f23c969)

```
square: false
columns: 1
type: grid
cards:
  - type: conditional
    conditions:
      - entity: sensor.doorbell_stream_status
        state: StreamStatus.IDLE
    card:
      show_state: true
      show_name: true
      type: picture-entity
      entity: camera.doorbell
      camera_image: camera.doorbell
      tap_action:
        action: call-service
        service: camera.turn_on
        data: {}
        target:
          entity_id: camera.doorbell
  - type: conditional
    conditions:
      - entity: sensor.doorbell_stream_status
        state: StreamStatus.PREPARING
    card:
      type: vertical-stack
      cards:
        - show_name: true
          show_icon: false
          type: button
          tap_action:
            action: call-service
            service: camera.turn_off
            data: {}
            target:
              entity_id: camera.doorbell
          entity: camera.doorbell
          name: Stop
        - type: custom:webrtc-camera
          entity: camera.doorbell
          url: sensor.doorbell_stream_url
```
![image](https://github.com/fuatakgun/eufy_security/assets/41022017/05d1c7e6-8bf7-4e29-a61e-e1c82f23c969)

```
type: vertical-stack
cards:
  - type: conditional
    conditions:
      - entity: sensor.doorbell_stream_status
        state: StreamStatus.IDLE
    card:
      show_state: true
      show_name: true
      camera_view: auto
      type: picture-entity
      entity: camera.doorbell
      camera_image: sensor.doorbell_last_camera_picture_url
      tap_action:
        action: call-service
        service: eufy_security.start_p2p_livestream
        target:
          entity_id: camera.doorbell
        data: {}
      image: camera.doorbell
  - type: conditional
    conditions:
      - entity: sensor.doorbell_stream_status
        state_not: StreamStatus.IDLE
    card:
      type: vertical-stack
      cards:
        - type: custom:webrtc-camera
          url: rtsp://127.0.0.1:8554/T8200*******
        - show_name: true
          show_icon: false
          type: button
          entity: button.doorbell_stop_p2p_stream
          name: Stop
          show_state: false
          tap_action:
            action: toggle
          hold_action:
            action: toggle
  - type: entities
    entities:
      - entity: sensor.doorbell_stream_status
        name: Status
      - entity: sensor.doorbell_wifi_signal_level
        secondary_info: none
        name: WiFi
    state_color: true

```
![image](https://github.com/fuatakgun/eufy_security/assets/41022017/b008ce92-943e-4535-8162-1c20e29303ab)

Why is that? Is there anything that I'm missing?
Thanks!
