### ISSUE TITLE
Working installation guide for HA Core users

### ISSUE THREAD

**Issue by kimme1024** [fuatakgun/eufy_security#845]
**Is your feature request related to a problem? Please describe.**
Following the tutorial I can't even get past step 1. See additional context below.

**Describe the solution you'd like**
A working tutorial for Core users, and no, supervised isn't an option, if it was, my life would be a lot easier.

**Describe alternatives you've considered**
NA

**Additional context**
For step 1, using these instructions (https://bropat.github.io/eufy-security-ws/#/docker), it doesn't find any devices. After adding my country code to the docker file it connects but it returns a JSON parse error. As it keeps on running I tried to connect to it anyway but the integration immediately states that I'm using a wrong ip/port.
For step 2, I'm getting following error `docker: invalid reference format: repository name must be lowercase.`

**Comment by kimme1024** [comment]
For me, at this point I'd already be happy when I'd have access to the motion trigger and the doorbell trigger as these are used by my automations. Don't really care about the video feed (would be a nice bonus tho...)

**Comment by golles** [comment]
Maybe my setup helps you to get it sorted out.
Make sure you've got the latest version of this custom_component installed, I've got master. I've made a 2nd account  (username/password) added for HA in the eufy app, 2FA is disabled for that account.

docker-compose.yaml
```yaml
version: '3'
services:

  eufy-security-ws:
    container_name: eufy-security-ws
    image: bropat/eufy-security-ws:latest
    restart: unless-stopped
    environment:
      - USERNAME=${EUFY_USERNAME}
      - PASSWORD=${EUFY_PASSWORD}
      - COUNTRY=${EUFY_COUNTRY}
      - TRUSTED_DEVICE_NAME=${EUFY_TRUSTED_DEVICE_NAME}
      - TZ=${TZ}

  rtsp-simple-server:
    container_name: rtsp-simple-server
    image: bluenviron/mediamtx:latest
    restart: unless-stopped
    environment:
      - RTSP_PROTOCOLS=tcp
      - TZ=${TZ}

  ...more containers...
```

Note that the `aler9/rtsp-simple-server` image (from the docs) is renamed/rebranded to `bluenviron/mediamtx` (cc @fuatakgun), I was to lazy to rename the `container_name`
Note2 I'm not exposing ports to the host, the containers live in the same docker network, so they can all reach each other.
Note3 I use a `.env` file, while testing you can just hardcode your config values.
Note4 The page you link mentions `network mode host`, I don't have this configured for any of my containers. The need for this is often a lack of proper configuration. I'm not sure if mDNS is required for this, but if so, I've set up avahi-daemon in reflector mode, see [this config](https://github.com/golles/Home-Assistant-Config/blob/main/packages/homekit.yaml#L1-L15).

After installing the custom_component in HA, I've got it configured like this:
<img width="931" alt="Scherm­afbeelding 2023-07-20 om 19 12 42" src="https://github.com/fuatakgun/eufy_security/assets/2211503/cedff4b8-fcbc-433f-b3e6-8267e99a067a">
Note: The host here is the `container_name` defined in the docker-compose file

Finally my doorbell automation, I've had trouble over time that the stream didn't always work, the binary_sensor for ringing did always work fine. The issue that I now have is that the snapshot image is outdated (more than a week old), for that there is already an issue #847

When someone rings my doorbell and the tv is on, it does pause, depending on the content that is playing. Then the web browser of the tv is opened with a link to the stream. This was for me the only way to view the doorbell camera.
See the [automation](https://github.com/golles/Home-Assistant-Config/blob/main/automations/deurbel.yaml), note that anything user-facing is in Dutch, and anything else is in English, most steps have an `alias` so I guess you'll figure out, the most interesting part is between lines 70-99.

Let me know if this is helpful or if you have any questions.
