### ISSUE TITLE
Example notification automation does not work correctly

### ISSUE THREAD

**Issue by eikowagenknecht** [fuatakgun/eufy_security#885]
**Describe the bug**

The example automation (https://github.com/fuatakgun/eufy_security#send-notification-with-thumbnail-from-home-assistant) shows not the current image but the one before. I think this is because the sensors trigger about 2s before the image is updated (at least for me this is the case).

**Expected behavior**

The current event picture should be shown

**Additional information**

This can be worked around by using a trigger like this (using the event image state):

```yaml
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - image.entrance_cam
condition:
  - condition: template
    value_template: >-
      {{
      as_timestamp(states.image.entrance_cam.last_changed)
      ==
      as_timestamp(states.image.entrance_cam.last_updated)
      }}

...
```

In the slightly more complex example the condition check would have to be put somewhere in the part where the sensor trigger conditions are evaluated.
