### ISSUE TITLE
Event Image in Storage

### ISSUE THREAD

**Issue by Streammet** [fuatakgun/eufy_security#922]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
Using the "Notification for Android TV" I would like to send Notification with an image. It is not possible because as far as I know the Integration can only send URL, Icon and local path. You may wonder why I dont use local path. The local path must be an image located in you storage and cant be an entity. It would be great if it is possible to have the image somehow saved on your storage.

**Describe alternatives you've considered**
Only Notification without an image.

**Additional context**
-

**Comment by fuatakgun** [comment]
Notification with an image? what does it need? 
if you need an URL, you can use image entity address.
if you need a stored file, you can save it yourself to disk, right?

**Comment by xbmcnut** [comment]
@Streammet Did you ever resolve this? I too am trying to send the doorbell image to my Android TV and this does not work
```
alias: Notify Family Room TV when Eufy doorbell is pushed
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.eufy_door_lock_ringing
    to: "on"
condition:
  - condition: state
    entity_id: media_player.family_room_tv_atvr
    state: "on"
action:
  - service: notify.google_tv_cc
    data:
      title: Eufy Lock
      message: Someone just pushed the doorbell
      data:
        duration: 10
        position: bottom-right
        fontsize: medium
        transparency: 25%
        color: indigo
        interrupt: 0
        image:
          path: /api/image_proxy/image.eufy_door_lock_event_image
mode: single
```
